// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID         int64     `json:"id"`
	TaskID     int64     `json:"task_id"`
	ResourceID int64     `json:"resource_id"`
	Quantity   int32     `json:"quantity"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Milestone struct {
	ID        int64          `json:"id"`
	ProcessID int64          `json:"process_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Color     sql.NullString `json:"color"`
	Date      time.Time      `json:"date"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Process struct {
	ID        int64          `json:"id"`
	ProjectID int64          `json:"project_id"`
	OwnerID   pgtype.Int8    `json:"owner_id"`
	Title     string         `json:"title"`
	Color     sql.NullString `json:"color"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	SortOrder int32          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Project struct {
	ID        int64          `json:"id"`
	OwnerID   pgtype.Int8    `json:"owner_id"`
	Code      string         `json:"code"`
	Color     sql.NullString `json:"color"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	Priority  int32          `json:"priority"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Resource struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Code      string         `json:"code"`
	Color     sql.NullString `json:"color"`
	OwnerID   int64          `json:"owner_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type Task struct {
	ID        int64          `json:"id"`
	ProcessID int64          `json:"process_id"`
	ParentID  pgtype.Int8    `json:"parent_id"`
	OwnerID   pgtype.Int8    `json:"owner_id"`
	Title     string         `json:"title"`
	Color     sql.NullString `json:"color"`
	Status    string         `json:"status"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	SortOrder int32          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
