// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auto_create.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const getAutoCreateConfig = `-- name: GetAutoCreateConfig :one
SELECT id, enabled, config
FROM project_auto_create
ORDER BY id
LIMIT 1
`

type GetAutoCreateConfigRow struct {
	ID      int64           `json:"id"`
	Enabled bool            `json:"enabled"`
	Config  json.RawMessage `json:"config"`
}

func (q *Queries) GetAutoCreateConfig(ctx context.Context) (GetAutoCreateConfigRow, error) {
	row := q.db.QueryRow(ctx, getAutoCreateConfig)
	var i GetAutoCreateConfigRow
	err := row.Scan(&i.ID, &i.Enabled, &i.Config)
	return i, err
}

const listExistingResources = `-- name: ListExistingResources :many
SELECT id
FROM resources
WHERE id = ANY($1::bigint[])
  AND deleted_at IS NULL
`

func (q *Queries) ListExistingResources(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listExistingResources, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExistingUsers = `-- name: ListExistingUsers :many
SELECT id
FROM users
WHERE id = ANY($1::bigint[])
  AND deleted_at IS NULL
`

func (q *Queries) ListExistingUsers(ctx context.Context, ids []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listExistingUsers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAutoCreateConfig = `-- name: UpsertAutoCreateConfig :one
INSERT INTO project_auto_create (id, enabled, config)
VALUES (1, $1, $2::jsonb)
ON CONFLICT (id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    config = EXCLUDED.config,
    updated_at = NOW()
RETURNING id, enabled, config, created_at, updated_at
`

type UpsertAutoCreateConfigParams struct {
	Enabled bool            `json:"enabled"`
	Config  json.RawMessage `json:"config"`
}

func (q *Queries) UpsertAutoCreateConfig(ctx context.Context, arg UpsertAutoCreateConfigParams) (ProjectAutoCreate, error) {
	row := q.db.QueryRow(ctx, upsertAutoCreateConfig, arg.Enabled, arg.Config)
	var i ProjectAutoCreate
	err := row.Scan(
		&i.ID,
		&i.Enabled,
		&i.Config,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
