// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignment.sql

package sqlc

import (
	"context"
)

const canUserCreateAssignment = `-- name: CanUserCreateAssignment :one
SELECT EXISTS (
    SELECT 1 FROM tasks t
	JOIN processes p ON p.id = t.process_id
    WHERE t.id = $1::bigint
	  AND t.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_create
`

type CanUserCreateAssignmentParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateAssignment(ctx context.Context, arg CanUserCreateAssignmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateAssignment, arg.TaskID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserDeleteAssignment = `-- name: CanUserDeleteAssignment :one
SELECT EXISTS (
    SELECT 1 FROM assignments a
	JOIN tasks t ON t.id = a.task_id
	JOIN processes p ON p.id = t.process_id
    WHERE a.id = $1::bigint
	  AND a.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserDeleteAssignmentParams struct {
	AssignmentID int64 `json:"assignment_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) CanUserDeleteAssignment(ctx context.Context, arg CanUserDeleteAssignmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserDeleteAssignment, arg.AssignmentID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const canUserUpdateAssignment = `-- name: CanUserUpdateAssignment :one
SELECT EXISTS (
    SELECT 1 FROM assignments a
	JOIN tasks t ON t.id = a.task_id
	JOIN processes p ON p.id = t.process_id
    WHERE a.id = $1::bigint
	  AND a.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserUpdateAssignmentParams struct {
	AssignmentID int64 `json:"assignment_id"`
	UserID       int64 `json:"user_id"`
}

func (q *Queries) CanUserUpdateAssignment(ctx context.Context, arg CanUserUpdateAssignmentParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserUpdateAssignment, arg.AssignmentID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (task_id, resource_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
`

type CreateAssignmentParams struct {
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment, arg.TaskID, arg.ResourceID, arg.Quantity)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
UPDATE assignments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteAssignment(ctx context.Context, assignmentID int64) error {
	_, err := q.db.Exec(ctx, deleteAssignment, assignmentID)
	return err
}

const findAssignment = `-- name: FindAssignment :one
SELECT id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
FROM assignments
WHERE id = $1
	AND deleted_at IS NULL
`

// TODO: write CanUserViewAssignment
func (q *Queries) FindAssignment(ctx context.Context, assignmentID int64) (Assignment, error) {
	row := q.db.QueryRow(ctx, findAssignment, assignmentID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssigments = `-- name: ListAssigments :many
SELECT id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
FROM assignments
WHERE deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) ListAssigments(ctx context.Context) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssigments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ResourceID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET
	quantity = $1,
	updated_at = NOW()
WHERE id = $2
	AND deleted_at IS NULL
RETURNING id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
`

type UpdateAssignmentParams struct {
	Quantity     int32 `json:"quantity"`
	AssignmentID int64 `json:"assignment_id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment, arg.Quantity, arg.AssignmentID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
