// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignment.sql

package sqlc

import (
	"context"
)

const countAssignments = `-- name: CountAssignments :one
SELECT COUNT(*)
FROM assignments a
JOIN tasks t ON t.id = a.task_id
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE a.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND pr.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR t.owner_id = $3::bigint OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
`

type CountAssignmentsParams struct {
	ScopeView string `json:"scope_view"`
	UserID    int64  `json:"user_id"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountAssignments(ctx context.Context, arg CountAssignmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssignments, arg.ScopeView, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (task_id, resource_id, quantity)
VALUES ($1, $2, $3::bigint)
ON CONFLICT (task_id, resource_id) WHERE deleted_at IS NULL
DO NOTHING
RETURNING id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
`

type CreateAssignmentParams struct {
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int64 `json:"quantity"`
}

// Идемпотентный create: если связка (task_id, resource_id) уже активна —
// ничего не вставляем; наличие существующей строки возвращает вызывающий
// код (репозиторий) через FindAssignmentByKey.
func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment, arg.TaskID, arg.ResourceID, arg.Quantity)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
UPDATE assignments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteAssignment(ctx context.Context, assignmentID int64) error {
	_, err := q.db.Exec(ctx, deleteAssignment, assignmentID)
	return err
}

const findAssignment = `-- name: FindAssignment :one
SELECT id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
FROM assignments
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) FindAssignment(ctx context.Context, assignmentID int64) (Assignment, error) {
	row := q.db.QueryRow(ctx, findAssignment, assignmentID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findAssignmentByKey = `-- name: FindAssignmentByKey :one
SELECT id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
FROM assignments
WHERE task_id = $1::bigint
	AND resource_id = $2::bigint
	AND deleted_at IS NULL
LIMIT 1
`

type FindAssignmentByKeyParams struct {
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
}

func (q *Queries) FindAssignmentByKey(ctx context.Context, arg FindAssignmentByKeyParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, findAssignmentByKey, arg.TaskID, arg.ResourceID)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssigments = `-- name: ListAssigments :many
SELECT a.id, a.task_id, a.resource_id, a.quantity, a.created_at, a.updated_at, a.deleted_at
FROM assignments a
JOIN tasks t ON t.id = a.task_id
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE a.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND pr.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR t.owner_id = $3::bigint OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
ORDER BY a.id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListAssigmentsParams struct {
	ScopeView  string `json:"scope_view"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

func (q *Queries) ListAssigments(ctx context.Context, arg ListAssigmentsParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssigments,
		arg.ScopeView,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Assignment{}
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ResourceID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(pr.owner_id, 0)::bigint AS project_owner,
       COALESCE(p.owner_id, 0)::bigint  AS process_owner
FROM assignments a
JOIN tasks t ON t.id = a.task_id
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE a.id = $1::bigint
	AND a.deleted_at IS NULL
	AND t.deleted_at IS NULL
	AND p.deleted_at IS NULL
	AND pr.deleted_at IS NULL
`

type OwnerChainRow struct {
	ProjectOwner int64 `json:"project_owner"`
	ProcessOwner int64 `json:"process_owner"`
}

func (q *Queries) OwnerChain(ctx context.Context, id int64) (OwnerChainRow, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var i OwnerChainRow
	err := row.Scan(&i.ProjectOwner, &i.ProcessOwner)
	return i, err
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET
	task_id = $1,
	resource_id = $2,
	quantity = $3::bigint,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, task_id, resource_id, quantity, created_at, updated_at, deleted_at
`

type UpdateAssignmentParams struct {
	TaskID       int64 `json:"task_id"`
	ResourceID   int64 `json:"resource_id"`
	Quantity     int64 `json:"quantity"`
	AssignmentID int64 `json:"assignment_id"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.TaskID,
		arg.ResourceID,
		arg.Quantity,
		arg.AssignmentID,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
