// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	auth2 "github.com/Koshsky/erp-backend/internal/auth"
	"github.com/Koshsky/erp-backend/internal/auth/delivery"
	service2 "github.com/Koshsky/erp-backend/internal/auth/service"
	"github.com/Koshsky/erp-backend/internal/config"
	"github.com/Koshsky/erp-backend/internal/database"
	"github.com/Koshsky/erp-backend/internal/logger"
	"github.com/Koshsky/erp-backend/internal/middleware/auth"
	"github.com/Koshsky/erp-backend/internal/middleware/rbac"
	"github.com/Koshsky/erp-backend/internal/planning"
	delivery3 "github.com/Koshsky/erp-backend/internal/planning/delivery"
	repository2 "github.com/Koshsky/erp-backend/internal/planning/repository"
	service3 "github.com/Koshsky/erp-backend/internal/planning/service"
	"github.com/Koshsky/erp-backend/internal/policies"
	"github.com/Koshsky/erp-backend/internal/project_mgmt"
	delivery8 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/delivery"
	repository6 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/repository"
	service8 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/service"
	delivery7 "github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/delivery"
	"github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/repository"
	service7 "github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/service"
	delivery6 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/delivery"
	repository5 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/repository"
	service6 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/service"
	delivery5 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/delivery"
	repository4 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/repository"
	service5 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/service"
	delivery4 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/delivery"
	repository3 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/repository"
	service4 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/service"
	"github.com/Koshsky/erp-backend/internal/security/jwt"
	"github.com/Koshsky/erp-backend/internal/server/profiler"
	"github.com/Koshsky/erp-backend/internal/timesheet"
	delivery12 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/delivery"
	repository10 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/repository"
	service12 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/service"
	delivery11 "github.com/Koshsky/erp-backend/internal/timesheet/employee/delivery"
	repository8 "github.com/Koshsky/erp-backend/internal/timesheet/employee/repository"
	service11 "github.com/Koshsky/erp-backend/internal/timesheet/employee/service"
	delivery9 "github.com/Koshsky/erp-backend/internal/timesheet/resource/delivery"
	repository7 "github.com/Koshsky/erp-backend/internal/timesheet/resource/repository"
	service9 "github.com/Koshsky/erp-backend/internal/timesheet/resource/service"
	delivery10 "github.com/Koshsky/erp-backend/internal/timesheet/state/delivery"
	repository9 "github.com/Koshsky/erp-backend/internal/timesheet/state/repository"
	service10 "github.com/Koshsky/erp-backend/internal/timesheet/state/service"
	"github.com/Koshsky/erp-backend/internal/user"
	delivery2 "github.com/Koshsky/erp-backend/internal/user/delivery"
	"github.com/Koshsky/erp-backend/internal/user/repository"
	"github.com/Koshsky/erp-backend/internal/user/service"
)

// Injectors from wire.go:

// InitializeApp builds the whole application dependency graph.
func InitializeApp() (*App, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	slogLogger, err := logger.ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	postgresConfig := config.ProvidePostgresConfig(configConfig)
	pool, err := database.ProvidePostgresDB(postgresConfig, slogLogger)
	if err != nil {
		return nil, err
	}
	jwtConfig := config.ProvideJWTConfig(configConfig)
	jwtService := jwt.ProvideJWTService(jwtConfig)
	middleware := auth.ProvideAuthMiddleware(slogLogger, jwtService)
	profilingConfig := config.ProvideProfilingConfig(configConfig)
	profilerProfiler := profiler.ProvideProfiler(profilingConfig, slogLogger)
	userRepository := repository.NewUserRepository(slogLogger, pool)
	userService := service.NewUserService(slogLogger, userRepository)
	authService := service2.NewAuthService(userService, jwtService)
	authHandler := delivery.NewAuthHandler(slogLogger, authService)
	module := auth2.ProvideModule(authHandler, slogLogger)
	userHandler := delivery2.NewUserHandler(slogLogger, userService)
	userModule := user.ProvideModule(userHandler)
	planningRepository := repository2.NewPlanningRepository(slogLogger, pool)
	planningService := service3.NewPlanningService(slogLogger, planningRepository)
	planningHandler := delivery3.NewPlanningHandler(slogLogger, planningService)
	planningModule := planning.ProvideModule(planningHandler)
	taskRepository := repository3.NewTaskRepository(slogLogger, pool)
	taskService := service4.NewTaskService(slogLogger, taskRepository)
	projectRepository := repository4.NewProjectRepository(slogLogger, pool)
	processRepository := repository5.NewProcessRepository(slogLogger, pool)
	milestoneRepository := postgres.NewMilestoneRepository(slogLogger, pool)
	assignmentRepository := repository6.NewAssignmentRepository(slogLogger, pool)
	resourceRepository := repository7.NewResourceRepository(slogLogger, pool)
	employeeRepository := repository8.NewEmployeeRepository(slogLogger, pool)
	data := ProvideRBACData(projectRepository, processRepository, taskRepository, milestoneRepository, assignmentRepository, resourceRepository, employeeRepository)
	v := policies.ProvideAll()
	rbacMiddleware := rbac.ProvideMiddleware(slogLogger, data, v)
	taskHandler := delivery4.NewTaskHandler(slogLogger, taskService, rbacMiddleware)
	projectService := service5.NewProjectService(slogLogger, projectRepository)
	projectHandler := delivery5.NewProjectHandler(slogLogger, projectService, rbacMiddleware)
	processService := service6.NewProcessService(slogLogger, processRepository)
	processHandler := delivery6.NewProcessHandler(slogLogger, processService, rbacMiddleware)
	milestoneService := service7.NewMilestoneService(slogLogger, milestoneRepository)
	milestoneHandler := delivery7.NewMilestoneHandler(slogLogger, milestoneService, rbacMiddleware)
	assignmentService := service8.NewAssignmentService(slogLogger, assignmentRepository)
	assignmentHandler := delivery8.NewAssignmentHandler(slogLogger, assignmentService, rbacMiddleware)
	project_mgmtModule := project_mgmt.ProvideModule(taskHandler, projectHandler, processHandler, milestoneHandler, assignmentHandler)
	resourceService := service9.NewResourceService(slogLogger, resourceRepository)
	resourceHandler := delivery9.NewResourceHandler(slogLogger, resourceService, rbacMiddleware)
	stateRepository := repository9.NewStateRepository(slogLogger, pool)
	stateService := service10.NewStateService(slogLogger, stateRepository)
	stateHandler := delivery10.NewStateHandler(slogLogger, stateService, rbacMiddleware)
	employeeService := service11.NewEmployeeService(slogLogger, employeeRepository)
	employeeHandler := delivery11.NewEmployeeHandler(slogLogger, employeeService, rbacMiddleware)
	calendarRepository := repository10.NewCalendarRepository(slogLogger, pool)
	calendarService := service12.NewCalendarService(slogLogger, calendarRepository)
	calendarHandler := delivery12.NewCalendarHandler(slogLogger, calendarService, rbacMiddleware)
	timesheetModule := timesheet.ProvideModule(resourceHandler, stateHandler, employeeHandler, calendarHandler)
	v2 := ProvideModules(module, userModule, planningModule, project_mgmtModule, timesheetModule)
	app, err := New(configConfig, slogLogger, pool, middleware, profilerProfiler, v2)
	if err != nil {
		return nil, err
	}
	return app, nil
}
