// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assignment.sql

package sqlc

import (
	"context"
)

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (task_id, resource_id, quantity)
VALUES ($1, $2, $3)
RETURNING id, task_id, resource_id, quantity
`

type CreateAssignmentParams struct {
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

type CreateAssignmentRow struct {
	ID         int64 `json:"id"`
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (CreateAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createAssignment, arg.TaskID, arg.ResourceID, arg.Quantity)
	var i CreateAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
UPDATE assignments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteAssignment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAssignment, id)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, task_id, resource_id, quantity
FROM assignments
WHERE id = $1
	AND deleted_at IS NULL
`

type GetAssignmentRow struct {
	ID         int64 `json:"id"`
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) GetAssignment(ctx context.Context, id int64) (GetAssignmentRow, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i GetAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
	)
	return i, err
}

const listAssignmentsByTaskID = `-- name: ListAssignmentsByTaskID :many
SELECT id, task_id, resource_id, quantity
FROM assignments
WHERE task_id = $1
	AND deleted_at IS NULL
ORDER BY id ASC
`

type ListAssignmentsByTaskIDRow struct {
	ID         int64 `json:"id"`
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) ListAssignmentsByTaskID(ctx context.Context, taskID int64) ([]ListAssignmentsByTaskIDRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentsByTaskID, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentsByTaskIDRow{}
	for rows.Next() {
		var i ListAssignmentsByTaskIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ResourceID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET
	quantity = $1,
	updated_at = NOW()
WHERE id = $2
	AND deleted_at IS NULL
RETURNING id, task_id, resource_id, quantity
`

type UpdateAssignmentParams struct {
	Quantity int32 `json:"quantity"`
	ID       int64 `json:"id"`
}

type UpdateAssignmentRow struct {
	ID         int64 `json:"id"`
	TaskID     int64 `json:"task_id"`
	ResourceID int64 `json:"resource_id"`
	Quantity   int32 `json:"quantity"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (UpdateAssignmentRow, error) {
	row := q.db.QueryRow(ctx, updateAssignment, arg.Quantity, arg.ID)
	var i UpdateAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ResourceID,
		&i.Quantity,
	)
	return i, err
}
