// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: milestones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (process_id, title, content, date)
VALUES ($1, $2, $3, $4)
RETURNING id, process_id, title, content, date
`

type CreateMilestoneParams struct {
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

type CreateMilestoneRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (CreateMilestoneRow, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProcessID,
		arg.Title,
		arg.Content,
		arg.Date,
	)
	var i CreateMilestoneRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
UPDATE milestones
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteMilestone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMilestone, id)
	return err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, process_id, title, content, date
FROM milestones
WHERE id = $1
	AND deleted_at IS NULL
`

type GetMilestoneRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

func (q *Queries) GetMilestone(ctx context.Context, id int64) (GetMilestoneRow, error) {
	row := q.db.QueryRow(ctx, getMilestone, id)
	var i GetMilestoneRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
	)
	return i, err
}

const listMilestonesByProcessID = `-- name: ListMilestonesByProcessID :many
SELECT id, process_id, title, content, date
FROM milestones
WHERE process_id = $1
	AND deleted_at IS NULL
ORDER BY date ASC, id ASC
`

type ListMilestonesByProcessIDRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

func (q *Queries) ListMilestonesByProcessID(ctx context.Context, processID int64) ([]ListMilestonesByProcessIDRow, error) {
	rows, err := q.db.Query(ctx, listMilestonesByProcessID, processID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMilestonesByProcessIDRow{}
	for rows.Next() {
		var i ListMilestonesByProcessIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.Title,
			&i.Content,
			&i.Date,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET
	title = $1,
	content = $2,
	date = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, process_id, title, content, date
`

type UpdateMilestoneParams struct {
	Title   string      `json:"title"`
	Content string      `json:"content"`
	Date    pgtype.Date `json:"date"`
	ID      int64       `json:"id"`
}

type UpdateMilestoneRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (UpdateMilestoneRow, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.Title,
		arg.Content,
		arg.Date,
		arg.ID,
	)
	var i UpdateMilestoneRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
	)
	return i, err
}
