// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: milestones.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canUserCreateMilestone = `-- name: CanUserCreateMilestone :one
SELECT EXISTS(
	SELECT 1 FROM processes p
	WHERE p.id = $1::bigint
		AND p.deleted_at IS NULL
		AND p.owner_id = $2::bigint
) AS can_create
`

type CanUserCreateMilestoneParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateMilestone(ctx context.Context, arg CanUserCreateMilestoneParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateMilestone, arg.ProcessID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserManageMilestone = `-- name: CanUserManageMilestone :one
SELECT EXISTS(
	SELECT 1 FROM milestones m
	JOIN processes p ON p.id = m.process_id
	WHERE m.id = $1::bigint
		AND m.deleted_at IS NULL
		AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserManageMilestoneParams struct {
	MilestoneID int64 `json:"milestone_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) CanUserManageMilestone(ctx context.Context, arg CanUserManageMilestoneParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserManageMilestone, arg.MilestoneID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (process_id, title, content, date)
VALUES ($1, $2, $3, $4)
RETURNING id, process_id, title, content, date, created_at, updated_at, deleted_at
`

type CreateMilestoneParams struct {
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      pgtype.Date `json:"date"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProcessID,
		arg.Title,
		arg.Content,
		arg.Date,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
UPDATE milestones
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteMilestone(ctx context.Context, milestoneID int64) error {
	_, err := q.db.Exec(ctx, deleteMilestone, milestoneID)
	return err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, process_id, title, content, date, created_at, updated_at, deleted_at
FROM milestones
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) GetMilestone(ctx context.Context, milestoneID int64) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, milestoneID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET
	title = $1,
	content = $2,
	date = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, process_id, title, content, date, created_at, updated_at, deleted_at
`

type UpdateMilestoneParams struct {
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Date        pgtype.Date `json:"date"`
	MilestoneID int64       `json:"milestone_id"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.Title,
		arg.Content,
		arg.Date,
		arg.MilestoneID,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
