// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process_details.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProcessTasksWithResources = `-- name: GetProcessTasksWithResources :many
SELECT
    t.id AS task_id,
    t.title AS task_title,
    t.start_date AS task_start_date,
    t.end_date AS task_end_date,
    a.id AS assignment_id,
    a.quantity AS assignment_quantity,
    r.id AS resource_id,
    r.title AS resource_title,
    r.code AS resource_code,
    r.quantity AS resource_quantity
FROM tasks t
LEFT JOIN assignments a ON a.task_id = t.id AND a.deleted_at IS NULL
LEFT JOIN resources r ON r.id = a.resource_id AND r.deleted_at IS NULL
WHERE t.process_id = $1::bigint
    AND t.deleted_at IS NULL
ORDER BY t.start_date ASC, t.end_date ASC, t.id ASC, a.id ASC
`

type GetProcessTasksWithResourcesRow struct {
	TaskID             int64       `json:"task_id"`
	TaskTitle          string      `json:"task_title"`
	TaskStartDate      pgtype.Date `json:"task_start_date"`
	TaskEndDate        pgtype.Date `json:"task_end_date"`
	AssignmentID       pgtype.Int8 `json:"assignment_id"`
	AssignmentQuantity pgtype.Int4 `json:"assignment_quantity"`
	ResourceID         pgtype.Int8 `json:"resource_id"`
	ResourceTitle      pgtype.Text `json:"resource_title"`
	ResourceCode       pgtype.Text `json:"resource_code"`
	ResourceQuantity   pgtype.Int4 `json:"resource_quantity"`
}

func (q *Queries) GetProcessTasksWithResources(ctx context.Context, processID int64) ([]GetProcessTasksWithResourcesRow, error) {
	rows, err := q.db.Query(ctx, getProcessTasksWithResources, processID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProcessTasksWithResourcesRow{}
	for rows.Next() {
		var i GetProcessTasksWithResourcesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TaskTitle,
			&i.TaskStartDate,
			&i.TaskEndDate,
			&i.AssignmentID,
			&i.AssignmentQuantity,
			&i.ResourceID,
			&i.ResourceTitle,
			&i.ResourceCode,
			&i.ResourceQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProcessWithProject = `-- name: GetProcessWithProject :one
SELECT
    p.id AS process_id,
    p.title AS process_title,
    p.start_date AS process_start_date,
    p.end_date AS process_end_date,
    pr.id AS project_id,
    pr.code AS project_code,
    pr.start_date AS project_start_date,
    pr.end_date AS project_end_date
FROM processes p
JOIN projects pr ON pr.id = p.project_id
WHERE p.id = $1::bigint
    AND p.deleted_at IS NULL
    AND pr.deleted_at IS NULL
`

type GetProcessWithProjectRow struct {
	ProcessID        int64       `json:"process_id"`
	ProcessTitle     string      `json:"process_title"`
	ProcessStartDate pgtype.Date `json:"process_start_date"`
	ProcessEndDate   pgtype.Date `json:"process_end_date"`
	ProjectID        int64       `json:"project_id"`
	ProjectCode      string      `json:"project_code"`
	ProjectStartDate pgtype.Date `json:"project_start_date"`
	ProjectEndDate   pgtype.Date `json:"project_end_date"`
}

func (q *Queries) GetProcessWithProject(ctx context.Context, processID int64) (GetProcessWithProjectRow, error) {
	row := q.db.QueryRow(ctx, getProcessWithProject, processID)
	var i GetProcessWithProjectRow
	err := row.Scan(
		&i.ProcessID,
		&i.ProcessTitle,
		&i.ProcessStartDate,
		&i.ProcessEndDate,
		&i.ProjectID,
		&i.ProjectCode,
		&i.ProjectStartDate,
		&i.ProjectEndDate,
	)
	return i, err
}
