// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: processes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (project_id, title, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, project_id, title, start_date, end_date
`

type CreateProcessParams struct {
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type CreateProcessRow struct {
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (CreateProcessRow, error) {
	row := q.db.QueryRow(ctx, createProcess,
		arg.ProjectID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreateProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :exec
UPDATE processes
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteProcess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProcess, id)
	return err
}

const getProcess = `-- name: GetProcess :one
SELECT id, project_id, title, start_date, end_date
FROM processes
WHERE id = $1
	AND deleted_at IS NULL
`

type GetProcessRow struct {
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) GetProcess(ctx context.Context, id int64) (GetProcessRow, error) {
	row := q.db.QueryRow(ctx, getProcess, id)
	var i GetProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listProcessesByProjectID = `-- name: ListProcessesByProjectID :many
SELECT id, project_id, title, start_date, end_date
FROM processes
WHERE project_id = $1
	AND deleted_at IS NULL
ORDER BY start_date ASC, end_date ASC, id ASC
`

type ListProcessesByProjectIDRow struct {
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListProcessesByProjectID(ctx context.Context, projectID int64) ([]ListProcessesByProjectIDRow, error) {
	rows, err := q.db.Query(ctx, listProcessesByProjectID, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProcessesByProjectIDRow{}
	for rows.Next() {
		var i ListProcessesByProjectIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcess = `-- name: UpdateProcess :one
UPDATE processes
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, project_id, title, start_date, end_date
`

type UpdateProcessParams struct {
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	ID        int64       `json:"id"`
}

type UpdateProcessRow struct {
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (UpdateProcessRow, error) {
	row := q.db.QueryRow(ctx, updateProcess,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i UpdateProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
