// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: processes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canUserCreateProcess = `-- name: CanUserCreateProcess :one
SELECT EXISTS(
	SELECT 1 FROM projects
	WHERE id = $1::bigint
		AND deleted_at IS NULL
		AND owner_id = $2::bigint
) AS can_create
`

type CanUserCreateProcessParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateProcess(ctx context.Context, arg CanUserCreateProcessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateProcess, arg.ProjectID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserManageProcess = `-- name: CanUserManageProcess :one
SELECT EXISTS (
    SELECT 1 FROM processes p
    JOIN projects pr ON pr.id = p.project_id
    WHERE p.id = $1::bigint
      AND p.deleted_at IS NULL
      AND pr.owner_id = $2::bigint
) AS can_manage
`

type CanUserManageProcessParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserManageProcess(ctx context.Context, arg CanUserManageProcessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserManageProcess, arg.ProcessID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (project_id, title, start_date, end_date, owner_id)
VALUES (
	$1::bigint,
	$2::text,
	$3::date,
	$4::date,
	$5::bigint
)
RETURNING id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateProcessParams struct {
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	OwnerID   int64       `json:"owner_id"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, createProcess,
		arg.ProjectID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :exec
UPDATE processes
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) DeleteProcess(ctx context.Context, processID int64) error {
	_, err := q.db.Exec(ctx, deleteProcess, processID)
	return err
}

const getDetailedProcess = `-- name: GetDetailedProcess :one
SELECT 
    p.id,
    p.project_id,
    p.owner_id,
    p.title,
    p.start_date,
    p.end_date,
    p.created_at,
    p.updated_at,
    p.deleted_at,
    COALESCE(
        (SELECT jsonb_agg(
            jsonb_build_object(
                'id', t.id,
                'process_id', t.process_id,
                'title', t.title,
                'start_date', t.start_date,
                'end_date', t.end_date,
                'created_at', t.created_at,
                'updated_at', t.updated_at,
                'deleted_at', t.deleted_at,
                'assignments', COALESCE(
                    (SELECT jsonb_agg(
                        jsonb_build_object(
                            'id', a.id,
                            'task_id', a.task_id,
                            'resource_id', a.resource_id,
                            'quantity', a.quantity
                        )
                        ORDER BY a.id
                    ) FROM assignments a WHERE a.task_id = t.id AND a.deleted_at IS NULL),
                    '[]'::jsonb
                )
            )
            ORDER BY t.id
        ) FROM tasks t WHERE t.process_id = p.id AND t.deleted_at IS NULL),
        '[]'::jsonb
    ) AS tasks,
    COALESCE(
        (SELECT jsonb_agg(
            jsonb_build_object(
                'id', m.id,
                'process_id', m.process_id,
                'title', m.title,
                'content', m.content,
                'date', m.date,
                'created_at', m.created_at,
                'updated_at', m.updated_at,
                'deleted_at', m.deleted_at
            )
            ORDER BY m.id
        ) FROM milestones m WHERE m.process_id = p.id AND m.deleted_at IS NULL),
        '[]'::jsonb
    ) AS milestones
FROM processes p
WHERE p.id = $1 AND p.deleted_at IS NULL
`

type GetDetailedProcessRow struct {
	ID         int64              `json:"id"`
	ProjectID  int64              `json:"project_id"`
	OwnerID    int64              `json:"owner_id"`
	Title      string             `json:"title"`
	StartDate  pgtype.Date        `json:"start_date"`
	EndDate    pgtype.Date        `json:"end_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
	Tasks      interface{}        `json:"tasks"`
	Milestones interface{}        `json:"milestones"`
}

func (q *Queries) GetDetailedProcess(ctx context.Context, id int64) (GetDetailedProcessRow, error) {
	row := q.db.QueryRow(ctx, getDetailedProcess, id)
	var i GetDetailedProcessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.Tasks,
		&i.Milestones,
	)
	return i, err
}

const getProcess = `-- name: GetProcess :one
SELECT id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM processes
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) GetProcess(ctx context.Context, id int64) (Process, error) {
	row := q.db.QueryRow(ctx, getProcess, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMilestonesByProcessIDs = `-- name: ListMilestonesByProcessIDs :many
SELECT id, process_id, title, content, date, created_at, updated_at, deleted_at FROM milestones 
WHERE process_id = ANY($1::bigint[]) AND deleted_at IS NULL 
ORDER BY id
`

func (q *Queries) ListMilestonesByProcessIDs(ctx context.Context, processIds []int64) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByProcessIDs, processIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.Title,
			&i.Content,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcesses = `-- name: ListProcesses :many
SELECT id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM processes p
WHERE p.deleted_at IS NULL
  AND (
    ($1::text != 'ДП') OR
    (p.owner_id = $2::bigint) OR
    (p.project_id IN (
        SELECT id FROM projects pr 
        WHERE pr.owner_id = $2::bigint
    ))
  )
ORDER BY 
    (SELECT priority FROM projects pr WHERE pr.id = p.project_id) ASC,
    p.start_date ASC, 
    p.end_date ASC, 
    p.id ASC
`

type ListProcessesParams struct {
	Role   string `json:"role"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ListProcesses(ctx context.Context, arg ListProcessesParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcesses, arg.Role, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksWithAssignmentsByProcessIDs = `-- name: ListTasksWithAssignmentsByProcessIDs :many
SELECT 
    t.id AS task_id,
    t.process_id,
    t.title AS task_title,
    t.start_date AS task_start_date,
    t.end_date AS task_end_date,
    t.created_at AS task_created_at,
    t.updated_at AS task_updated_at,
    t.deleted_at AS task_deleted_at,
    a.id AS assignment_id,
    a.task_id AS assignment_task_id,
    a.resource_id,
    a.quantity AS assignment_quantity,
    a.created_at AS assignment_created_at,
    a.updated_at AS assignment_updated_at,
    a.deleted_at AS assignment_deleted_at
FROM tasks t
LEFT JOIN assignments a ON a.task_id = t.id AND a.deleted_at IS NULL
WHERE t.process_id = ANY($1::bigint[]) AND t.deleted_at IS NULL
ORDER BY t.id, a.id
`

type ListTasksWithAssignmentsByProcessIDsRow struct {
	TaskID              int64              `json:"task_id"`
	ProcessID           int64              `json:"process_id"`
	TaskTitle           string             `json:"task_title"`
	TaskStartDate       pgtype.Date        `json:"task_start_date"`
	TaskEndDate         pgtype.Date        `json:"task_end_date"`
	TaskCreatedAt       pgtype.Timestamptz `json:"task_created_at"`
	TaskUpdatedAt       pgtype.Timestamptz `json:"task_updated_at"`
	TaskDeletedAt       pgtype.Timestamptz `json:"task_deleted_at"`
	AssignmentID        pgtype.Int8        `json:"assignment_id"`
	AssignmentTaskID    pgtype.Int8        `json:"assignment_task_id"`
	ResourceID          pgtype.Int8        `json:"resource_id"`
	AssignmentQuantity  pgtype.Int4        `json:"assignment_quantity"`
	AssignmentCreatedAt pgtype.Timestamptz `json:"assignment_created_at"`
	AssignmentUpdatedAt pgtype.Timestamptz `json:"assignment_updated_at"`
	AssignmentDeletedAt pgtype.Timestamptz `json:"assignment_deleted_at"`
}

func (q *Queries) ListTasksWithAssignmentsByProcessIDs(ctx context.Context, processIds []int64) ([]ListTasksWithAssignmentsByProcessIDsRow, error) {
	rows, err := q.db.Query(ctx, listTasksWithAssignmentsByProcessIDs, processIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksWithAssignmentsByProcessIDsRow{}
	for rows.Next() {
		var i ListTasksWithAssignmentsByProcessIDsRow
		if err := rows.Scan(
			&i.TaskID,
			&i.ProcessID,
			&i.TaskTitle,
			&i.TaskStartDate,
			&i.TaskEndDate,
			&i.TaskCreatedAt,
			&i.TaskUpdatedAt,
			&i.TaskDeletedAt,
			&i.AssignmentID,
			&i.AssignmentTaskID,
			&i.ResourceID,
			&i.AssignmentQuantity,
			&i.AssignmentCreatedAt,
			&i.AssignmentUpdatedAt,
			&i.AssignmentDeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcess = `-- name: UpdateProcess :one
UPDATE processes
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	owner_id = COALESCE($4, owner_id),
	updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $5::bigint
RETURNING id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateProcessParams struct {
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	OwnerID   int64       `json:"owner_id"`
	ProcessID int64       `json:"process_id"`
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, updateProcess,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
		arg.ProcessID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
