// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (code, start_date, end_date, priority)
VALUES ($1, $2, $3, $4)
RETURNING id, code, start_date, end_date, priority
`

type CreateProjectParams struct {
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
}

type CreateProjectRow struct {
	ID        int64       `json:"id"`
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Code,
		arg.StartDate,
		arg.EndDate,
		arg.Priority,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProject, id)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, code, start_date, end_date, priority
FROM projects
WHERE id = $1
	AND deleted_at IS NULL
`

type GetProjectRow struct {
	ID        int64       `json:"id"`
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
}

func (q *Queries) GetProject(ctx context.Context, id int64) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, code, start_date, end_date, priority
FROM projects
WHERE deleted_at IS NULL
ORDER BY priority ASC, start_date ASC, id ASC
`

type ListProjectsRow struct {
	ID        int64       `json:"id"`
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
}

func (q *Queries) ListProjects(ctx context.Context) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsRow{}
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
	code = $1,
	priority = $2,
	start_date = $3,
	end_date = $4,
	updated_at = NOW()
WHERE id = $5
	AND deleted_at IS NULL
RETURNING id, code, start_date, end_date, priority
`

type UpdateProjectParams struct {
	Code      string      `json:"code"`
	Priority  int32       `json:"priority"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	ID        int64       `json:"id"`
}

type UpdateProjectRow struct {
	ID        int64       `json:"id"`
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Code,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
	)
	return i, err
}
