// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canUserCreateProject = `-- name: CanUserCreateProject :one
SELECT EXISTS (
    SELECT 1 FROM users 
    WHERE id = $1::bigint 
      AND role = 'ДП'
      AND deleted_at IS NULL
) AS can_create
`

func (q *Queries) CanUserCreateProject(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateProject, userID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserManageProject = `-- name: CanUserManageProject :one
SELECT EXISTS (
    SELECT 1 FROM projects p
    WHERE p.id = $1::bigint
      AND p.deleted_at IS NULL
      AND EXISTS (
          SELECT 1 FROM users u
          WHERE u.id = $2::bigint
            AND u.role = 'ДП'
            AND u.deleted_at IS NULL
      )
) AS can_manage
`

type CanUserManageProjectParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserManageProject(ctx context.Context, arg CanUserManageProjectParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserManageProject, arg.ProjectID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (code, start_date, end_date, priority, owner_id)
VALUES (
  $1::text,
  $2::date,
  $3::date,
  $4,
  $5::bigint
)
RETURNING id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	Code      string      `json:"code"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Priority  int32       `json:"priority"`
	OwnerID   int64       `json:"owner_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Code,
		arg.StartDate,
		arg.EndDate,
		arg.Priority,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) DeleteProject(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, deleteProject, projectID)
	return err
}

const getProject = `-- name: GetProject :one
SELECT id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
  AND id = $1::bigint
`

func (q *Queries) GetProject(ctx context.Context, projectID int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, projectID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
  AND (
    $1::text != 'ДП' OR
    owner_id = $2::bigint
  )
ORDER BY priority ASC, start_date ASC, id ASC
`

type ListProjectsParams struct {
	Role   string `json:"role"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Role, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
	code = $1,
	priority = $2,
	start_date = $3,
	end_date = $4,
  owner_id = $5,
	updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $6::bigint
RETURNING id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Code      string      `json:"code"`
	Priority  int32       `json:"priority"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	OwnerID   int64       `json:"owner_id"`
	ProjectID int64       `json:"project_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Code,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
		arg.ProjectID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
