// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (title, code, quantity)
VALUES ($1, $2, $3)
RETURNING id, title, code, quantity
`

type CreateResourceParams struct {
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
}

type CreateResourceRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (CreateResourceRow, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Title, arg.Code, arg.Quantity)
	var i CreateResourceRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE resources
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, code, quantity
FROM resources
WHERE id = $1
    AND deleted_at IS NULL
`

type GetResourceRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) GetResource(ctx context.Context, id int64) (GetResourceRow, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i GetResourceRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
	)
	return i, err
}

const getResourceUsage = `-- name: GetResourceUsage :many
SELECT
    r.id,
    r.title,
    r.code,
    r.quantity AS total_quantity,
    COALESCE(SUM(a.quantity), 0)::BIGINT AS used_quantity,
    (r.quantity - COALESCE(SUM(a.quantity), 0))::BIGINT AS available_quantity
FROM resources r
LEFT JOIN assignments a ON a.resource_id = r.id
    AND a.deleted_at IS NULL
LEFT JOIN tasks t ON a.task_id = t.id
    AND t.start_date <= $1::date
    AND t.end_date > $1::date
    AND t.deleted_at IS NULL
WHERE r.deleted_at IS NULL
GROUP BY r.id, r.title, r.quantity
ORDER BY r.title ASC
`

type GetResourceUsageRow struct {
	ID                int64  `json:"id"`
	Title             string `json:"title"`
	Code              string `json:"code"`
	TotalQuantity     int32  `json:"total_quantity"`
	UsedQuantity      int64  `json:"used_quantity"`
	AvailableQuantity int64  `json:"available_quantity"`
}

func (q *Queries) GetResourceUsage(ctx context.Context, targetDate pgtype.Date) ([]GetResourceUsageRow, error) {
	rows, err := q.db.Query(ctx, getResourceUsage, targetDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetResourceUsageRow{}
	for rows.Next() {
		var i GetResourceUsageRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.TotalQuantity,
			&i.UsedQuantity,
			&i.AvailableQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, title, code, quantity
FROM resources
WHERE deleted_at IS NULL
ORDER BY title ASC, id ASC
`

type ListResourcesRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) ListResources(ctx context.Context) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
	title = $1,
	code = $2,
	quantity = $3,
	updated_at = NOW()
WHERE id = $4
    AND deleted_at IS NULL
RETURNING id, title, code, quantity
`

type UpdateResourceParams struct {
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
	ID       int64  `json:"id"`
}

type UpdateResourceRow struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int32  `json:"quantity"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (UpdateResourceRow, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Title,
		arg.Code,
		arg.Quantity,
		arg.ID,
	)
	var i UpdateResourceRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
	)
	return i, err
}
