// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const canUserCreateTask = `-- name: CanUserCreateTask :one
SELECT EXISTS (
    SELECT 1 FROM processes p
    WHERE p.id = $1::bigint
	  AND p.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_create
`

type CanUserCreateTaskParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateTask(ctx context.Context, arg CanUserCreateTaskParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateTask, arg.ProcessID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserManageTask = `-- name: CanUserManageTask :one
SELECT EXISTS (
    SELECT 1 FROM tasks t
    JOIN processes p ON t.process_id = p.id
    WHERE t.id = $1::bigint
	  AND t.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserManageTaskParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CanUserManageTask(ctx context.Context, arg CanUserManageTaskParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserManageTask, arg.TaskID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (process_id, title, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProcessID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const getDetailedTask = `-- name: GetDetailedTask :one
SELECT 
    t.id,
    t.process_id,
    t.title,
    t.start_date,
    t.end_date,
    COALESCE(
        (SELECT json_agg(
            json_build_object(
                'id', a.id,
                'task_id', a.task_id,
                'resource_id', a.resource_id,
                'quantity', a.quantity
            )
            ORDER BY a.id
        ) FROM assignments a WHERE a.task_id = t.id),
        '[]'::json
    )::jsonb AS assignments
FROM tasks t
WHERE t.id = $1
`

type GetDetailedTaskRow struct {
	ID          int64       `json:"id"`
	ProcessID   int64       `json:"process_id"`
	Title       string      `json:"title"`
	StartDate   pgtype.Date `json:"start_date"`
	EndDate     pgtype.Date `json:"end_date"`
	Assignments []byte      `json:"assignments"`
}

func (q *Queries) GetDetailedTask(ctx context.Context, id int64) (GetDetailedTaskRow, error) {
	row := q.db.QueryRow(ctx, getDetailedTask, id)
	var i GetDetailedTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Assignments,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) GetTask(ctx context.Context, resourceID int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, resourceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	TaskID    int64       `json:"task_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
