// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (process_id, title, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, process_id, title, start_date, end_date
`

type CreateTaskParams struct {
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

type CreateTaskRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (CreateTaskRow, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProcessID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteTask(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, process_id, title, start_date, end_date
FROM tasks
WHERE id = $1
	AND deleted_at IS NULL
`

type GetTaskRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) GetTask(ctx context.Context, id int64) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i GetTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listTasksByProcessID = `-- name: ListTasksByProcessID :many
SELECT id, process_id, title, start_date, end_date
FROM tasks
WHERE process_id = $1
	AND deleted_at IS NULL
ORDER BY start_date ASC, end_date ASC, id ASC
`

type ListTasksByProcessIDRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) ListTasksByProcessID(ctx context.Context, processID int64) ([]ListTasksByProcessIDRow, error) {
	rows, err := q.db.Query(ctx, listTasksByProcessID, processID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByProcessIDRow{}
	for rows.Next() {
		var i ListTasksByProcessIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, process_id, title, start_date, end_date
`

type UpdateTaskParams struct {
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	ID        int64       `json:"id"`
}

type UpdateTaskRow struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (UpdateTaskRow, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i UpdateTaskRow
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
