// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Resource struct {
	ID        int64          `json:"id"`
	Title     string         `json:"title"`
	Code      string         `json:"code"`
	Color     sql.NullString `json:"color"`
	OwnerID   int64          `json:"owner_id"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
