// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package sqlc

import (
	"context"
	"time"
)

const countEmployeesByResourceID = `-- name: CountEmployeesByResourceID :one
SELECT COUNT(*)::bigint
FROM employees
WHERE resource_id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) CountEmployeesByResourceID(ctx context.Context, resourceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployeesByResourceID, resourceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (title, code)
VALUES ($1, $2)
RETURNING id, title, code, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	Title string `json:"title"`
	Code  string `json:"code"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Title, arg.Code)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE resources
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteResource(ctx context.Context, resourceID int64) error {
	_, err := q.db.Exec(ctx, deleteResource, resourceID)
	return err
}

const findResource = `-- name: FindResource :one
SELECT r.id, r.code, r.title,
    COUNT(e.id) FILTER (WHERE e.deleted_at IS NULL)::bigint AS employees_count,
    r.created_at, r.updated_at, r.deleted_at
FROM resources r
LEFT JOIN employees e ON e.resource_id = r.id
WHERE r.deleted_at IS NULL
	AND r.id = $1::bigint
GROUP BY r.id, r.code, r.title, r.created_at, r.updated_at, r.deleted_at
`

type FindResourceRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	EmployeesCount int64       `json:"employees_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	DeletedAt      **time.Time `json:"deleted_at"`
}

func (q *Queries) FindResource(ctx context.Context, resourceID int64) (FindResourceRow, error) {
	row := q.db.QueryRow(ctx, findResource, resourceID)
	var i FindResourceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.EmployeesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT r.id, r.code, r.title,
    COUNT(e.id) FILTER (WHERE e.deleted_at IS NULL)::bigint AS employees_count,
    r.created_at, r.updated_at, r.deleted_at
FROM resources r
LEFT JOIN employees e ON e.resource_id = r.id
WHERE r.deleted_at IS NULL
GROUP BY r.id, r.code, r.title, r.created_at, r.updated_at, r.deleted_at
ORDER BY r.id ASC
`

type ListResourcesRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	EmployeesCount int64       `json:"employees_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	DeletedAt      **time.Time `json:"deleted_at"`
}

func (q *Queries) ListResources(ctx context.Context) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.EmployeesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
	title = $1,
	code = $2,
	updated_at = NOW()
WHERE id = $3
    AND deleted_at IS NULL
RETURNING id, title, code, created_at, updated_at, deleted_at
`

type UpdateResourceParams struct {
	Title      string `json:"title"`
	Code       string `json:"code"`
	ResourceID int64  `json:"resource_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource, arg.Title, arg.Code, arg.ResourceID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
