// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMember = `-- name: AddMember :exec
INSERT INTO resource_members (resource_id, user_id)
VALUES ($1::bigint, $2::bigint)
ON CONFLICT DO NOTHING
`

type AddMemberParams struct {
	ResourceID int64 `json:"resource_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.ResourceID, arg.UserID)
	return err
}

const countMembersByResourceID = `-- name: CountMembersByResourceID :one
SELECT COUNT(*)::bigint
FROM resource_members
WHERE resource_id = $1::bigint
`

func (q *Queries) CountMembersByResourceID(ctx context.Context, resourceID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countMembersByResourceID, resourceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countResources = `-- name: CountResources :one
SELECT COUNT(*)
FROM resources
WHERE deleted_at IS NULL
  AND ($1::text = 'admin' OR owner_id = $2::bigint)
  AND ($3::bigint = 0 OR owner_id = $3::bigint)
`

type CountResourcesParams struct {
	Role    string `json:"role"`
	UserID  int64  `json:"user_id"`
	OwnerID int64  `json:"owner_id"`
}

func (q *Queries) CountResources(ctx context.Context, arg CountResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResources, arg.Role, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (title, code, owner_id)
VALUES ($1, $2, $3)
RETURNING id, title, code, owner_id, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	Title   string `json:"title"`
	Code    string `json:"code"`
	OwnerID int64  `json:"owner_id"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Title, arg.Code, arg.OwnerID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE resources
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteResource(ctx context.Context, resourceID int64) error {
	_, err := q.db.Exec(ctx, deleteResource, resourceID)
	return err
}

const findResource = `-- name: FindResource :one
SELECT r.id, r.code, r.title, r.owner_id,
    COUNT(rm.user_id)::bigint AS employees_count,
    r.created_at, r.updated_at, r.deleted_at
FROM resources r
LEFT JOIN resource_members rm ON rm.resource_id = r.id
WHERE r.deleted_at IS NULL
	AND r.id = $1::bigint
GROUP BY r.id, r.code, r.title, r.owner_id, r.created_at, r.updated_at, r.deleted_at
`

type FindResourceRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	OwnerID        int64       `json:"owner_id"`
	EmployeesCount int64       `json:"employees_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	DeletedAt      **time.Time `json:"deleted_at"`
}

func (q *Queries) FindResource(ctx context.Context, resourceID int64) (FindResourceRow, error) {
	row := q.db.QueryRow(ctx, findResource, resourceID)
	var i FindResourceRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Title,
		&i.OwnerID,
		&i.EmployeesCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserManager = `-- name: FindUserManager :one
SELECT manager_id
FROM users
WHERE id = $1::bigint
  AND deleted_at IS NULL
`

func (q *Queries) FindUserManager(ctx context.Context, userID int64) (pgtype.Int8, error) {
	row := q.db.QueryRow(ctx, findUserManager, userID)
	var manager_id pgtype.Int8
	err := row.Scan(&manager_id)
	return manager_id, err
}

const listMembersByResourceID = `-- name: ListMembersByResourceID :many

SELECT u.id, u.name, u.role, u.position, u.hire_date, u.termination_date, u.manager_id
FROM resource_members rm
JOIN users u ON u.id = rm.user_id
WHERE rm.resource_id = $1::bigint
  AND u.deleted_at IS NULL
ORDER BY u.id ASC
`

type ListMembersByResourceIDRow struct {
	ID              int64       `json:"id"`
	Name            string      `json:"name"`
	Role            string      `json:"role"`
	Position        string      `json:"position"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
}

// ================= resource members =================
func (q *Queries) ListMembersByResourceID(ctx context.Context, resourceID int64) ([]ListMembersByResourceIDRow, error) {
	rows, err := q.db.Query(ctx, listMembersByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersByResourceIDRow{}
	for rows.Next() {
		var i ListMembersByResourceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.Position,
			&i.HireDate,
			&i.TerminationDate,
			&i.ManagerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT r.id, r.code, r.title, r.owner_id,
    COUNT(rm.user_id)::bigint AS employees_count,
    r.created_at, r.updated_at, r.deleted_at
FROM resources r
LEFT JOIN resource_members rm ON rm.resource_id = r.id
WHERE r.deleted_at IS NULL
  AND ($1::text = 'admin' OR r.owner_id = $2::bigint)
  AND ($3::bigint = 0 OR r.owner_id = $3::bigint)
GROUP BY r.id, r.code, r.title, r.owner_id, r.created_at, r.updated_at, r.deleted_at
ORDER BY r.id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListResourcesParams struct {
	Role       string `json:"role"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

type ListResourcesRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	OwnerID        int64       `json:"owner_id"`
	EmployeesCount int64       `json:"employees_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	DeletedAt      **time.Time `json:"deleted_at"`
}

func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources,
		arg.Role,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.OwnerID,
			&i.EmployeesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByOwnerID = `-- name: ListResourcesByOwnerID :many
SELECT r.id, r.code, r.title, r.owner_id,
    COUNT(rm.user_id)::bigint AS employees_count,
    r.created_at, r.updated_at, r.deleted_at
FROM resources r
LEFT JOIN resource_members rm ON rm.resource_id = r.id
WHERE r.deleted_at IS NULL
	AND r.owner_id = $1::bigint
GROUP BY r.id, r.code, r.title, r.owner_id, r.created_at, r.updated_at, r.deleted_at
ORDER BY r.id ASC
`

type ListResourcesByOwnerIDRow struct {
	ID             int64       `json:"id"`
	Code           string      `json:"code"`
	Title          string      `json:"title"`
	OwnerID        int64       `json:"owner_id"`
	EmployeesCount int64       `json:"employees_count"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
	DeletedAt      **time.Time `json:"deleted_at"`
}

func (q *Queries) ListResourcesByOwnerID(ctx context.Context, ownerID int64) ([]ListResourcesByOwnerIDRow, error) {
	rows, err := q.db.Query(ctx, listResourcesByOwnerID, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesByOwnerIDRow{}
	for rows.Next() {
		var i ListResourcesByOwnerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Title,
			&i.OwnerID,
			&i.EmployeesCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(owner_id, 0)::bigint AS owner_id
FROM resources
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) OwnerChain(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM resource_members
WHERE resource_id = $1::bigint
  AND user_id = $2::bigint
`

type RemoveMemberParams struct {
	ResourceID int64 `json:"resource_id"`
	UserID     int64 `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ResourceID, arg.UserID)
	return err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
	title = $1,
	code = $2,
	owner_id = $3,
	updated_at = NOW()
WHERE id = $4
    AND deleted_at IS NULL
RETURNING id, title, code, owner_id, created_at, updated_at, deleted_at
`

type UpdateResourceParams struct {
	Title      string `json:"title"`
	Code       string `json:"code"`
	OwnerID    int64  `json:"owner_id"`
	ResourceID int64  `json:"resource_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Title,
		arg.Code,
		arg.OwnerID,
		arg.ResourceID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
