// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: states.sql

package sqlc

import (
	"context"
)

const createState = `-- name: CreateState :one
INSERT INTO states (code, name, is_available)
VALUES ($1, $2, $3)
ON CONFLICT ON CONSTRAINT states_code_key
DO NOTHING
RETURNING id, code, name, is_available, created_at, updated_at, deleted_at
`

type CreateStateParams struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	IsAvailable bool   `json:"is_available"`
}

// Idempotent create by business key code: if the code already exists we
// insert nothing; the calling code (repository) turns the conflict into 409.
func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRow(ctx, createState, arg.Code, arg.Name, arg.IsAvailable)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteState = `-- name: DeleteState :exec
UPDATE states
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteState(ctx context.Context, stateID int64) error {
	_, err := q.db.Exec(ctx, deleteState, stateID)
	return err
}

const findState = `-- name: FindState :one
SELECT id, code, name, is_available, created_at, updated_at, deleted_at FROM states
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) FindState(ctx context.Context, stateID int64) (State, error) {
	row := q.db.QueryRow(ctx, findState, stateID)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listStates = `-- name: ListStates :many
SELECT id, code, name, is_available, created_at, updated_at, deleted_at FROM states
WHERE deleted_at IS NULL
ORDER BY id ASC
`

func (q *Queries) ListStates(ctx context.Context) ([]State, error) {
	rows, err := q.db.Query(ctx, listStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []State{}
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateState = `-- name: UpdateState :one
UPDATE states
SET
	code = $1,
	name = $2,
	is_available = $3,
	updated_at = NOW()
WHERE id = $4
	AND deleted_at IS NULL
RETURNING id, code, name, is_available, created_at, updated_at, deleted_at
`

type UpdateStateParams struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	IsAvailable bool   `json:"is_available"`
	StateID     int64  `json:"state_id"`
}

func (q *Queries) UpdateState(ctx context.Context, arg UpdateStateParams) (State, error) {
	row := q.db.QueryRow(ctx, updateState,
		arg.Code,
		arg.Name,
		arg.IsAvailable,
		arg.StateID,
	)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsAvailable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
