// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: dependencies.sql

package sqlc

import (
	"context"

	"github.com/Koshsky/erp-backend/pkg/date"
)

const createDependency = `-- name: CreateDependency :one
INSERT INTO task_dependencies (task_id, depends_on_task_id, type)
VALUES ($1, $2, $3)
RETURNING id, task_id, depends_on_task_id, type, created_at, updated_at
`

type CreateDependencyParams struct {
	TaskID          int64  `json:"task_id"`
	DependsOnTaskID int64  `json:"depends_on_task_id"`
	Type            string `json:"type"`
}

func (q *Queries) CreateDependency(ctx context.Context, arg CreateDependencyParams) (TaskDependency, error) {
	row := q.db.QueryRow(ctx, createDependency, arg.TaskID, arg.DependsOnTaskID, arg.Type)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDependency = `-- name: DeleteDependency :exec
DELETE FROM task_dependencies
WHERE id = $1
`

func (q *Queries) DeleteDependency(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDependency, id)
	return err
}

const dependencyCycle = `-- name: DependencyCycle :one
WITH RECURSIVE walk AS (
	SELECT depends_on, 1 AS depth
	FROM (
		SELECT depends_on_task_id AS depends_on
		FROM task_dependencies
		WHERE task_id = $2::bigint
	) start_edges
	UNION ALL
	SELECT d.depends_on_task_id, w.depth + 1
	FROM walk w
	JOIN task_dependencies d ON d.task_id = w.depends_on
	WHERE w.depth < 100
)
SELECT EXISTS (SELECT 1 FROM walk WHERE depends_on = $1::bigint)
`

type DependencyCycleParams struct {
	TaskID          int64 `json:"task_id"`
	DependsOnTaskID int64 `json:"depends_on_task_id"`
}

// True when inserting task_id -> depends_on_task_id would close a cycle:
// the predecessor already (transitively) depends on the dependent task.
// Walks predecessor links (successor -> predecessor) from the predecessor
// with a depth cap (a guard against corrupted graphs).
func (q *Queries) DependencyCycle(ctx context.Context, arg DependencyCycleParams) (bool, error) {
	row := q.db.QueryRow(ctx, dependencyCycle, arg.TaskID, arg.DependsOnTaskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dependencyExists = `-- name: DependencyExists :one
SELECT EXISTS (
    SELECT 1 FROM task_dependencies
    WHERE task_id = $1::bigint
      AND depends_on_task_id = $2::bigint
)
`

type DependencyExistsParams struct {
	TaskID          int64 `json:"task_id"`
	DependsOnTaskID int64 `json:"depends_on_task_id"`
}

func (q *Queries) DependencyExists(ctx context.Context, arg DependencyExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, dependencyExists, arg.TaskID, arg.DependsOnTaskID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findDependency = `-- name: FindDependency :one
SELECT id, task_id, depends_on_task_id, type, created_at, updated_at
FROM task_dependencies
WHERE id = $1::bigint
`

func (q *Queries) FindDependency(ctx context.Context, id int64) (TaskDependency, error) {
	row := q.db.QueryRow(ctx, findDependency, id)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findTaskDates = `-- name: FindTaskDates :one
SELECT start_date, end_date
FROM tasks
WHERE id = $1::bigint
`

type FindTaskDatesRow struct {
	StartDate date.Date `json:"start_date"`
	EndDate   date.Date `json:"end_date"`
}

func (q *Queries) FindTaskDates(ctx context.Context, taskID int64) (FindTaskDatesRow, error) {
	row := q.db.QueryRow(ctx, findTaskDates, taskID)
	var i FindTaskDatesRow
	err := row.Scan(&i.StartDate, &i.EndDate)
	return i, err
}

const listDependenciesByTask = `-- name: ListDependenciesByTask :many
SELECT id, task_id, depends_on_task_id, type, created_at, updated_at
FROM task_dependencies
WHERE task_id = $1::bigint
ORDER BY id ASC
`

// Incoming links of a task (its predecessors), in creation order.
func (q *Queries) ListDependenciesByTask(ctx context.Context, taskID int64) ([]TaskDependency, error) {
	rows, err := q.db.Query(ctx, listDependenciesByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskDependency{}
	for rows.Next() {
		var i TaskDependency
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.DependsOnTaskID,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskConstraints = `-- name: ListTaskConstraints :many
SELECT
	td.id,
	td.type,
	p.id AS pred_id,
	p.title AS pred_title,
	p.start_date AS pred_start_date,
	p.end_date AS pred_end_date
FROM task_dependencies td
JOIN tasks p ON p.id = td.depends_on_task_id
WHERE td.task_id = $1::bigint
ORDER BY td.id ASC
`

type ListTaskConstraintsRow struct {
	ID            int64     `json:"id"`
	Type          string    `json:"type"`
	PredID        int64     `json:"pred_id"`
	PredTitle     string    `json:"pred_title"`
	PredStartDate date.Date `json:"pred_start_date"`
	PredEndDate   date.Date `json:"pred_end_date"`
}

// Incoming scheduling constraints of a task (the task as a successor): each
// edge with its type and the predecessor's current dates + display title.
// Used by the date guard (CheckTaskDates) and by the editor.
func (q *Queries) ListTaskConstraints(ctx context.Context, taskID int64) ([]ListTaskConstraintsRow, error) {
	rows, err := q.db.Query(ctx, listTaskConstraints, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskConstraintsRow{}
	for rows.Next() {
		var i ListTaskConstraintsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.PredID,
			&i.PredTitle,
			&i.PredStartDate,
			&i.PredEndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDependencyType = `-- name: UpdateDependencyType :one
UPDATE task_dependencies
SET type = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, task_id, depends_on_task_id, type, created_at, updated_at
`

type UpdateDependencyTypeParams struct {
	Type string `json:"type"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateDependencyType(ctx context.Context, arg UpdateDependencyTypeParams) (TaskDependency, error) {
	row := q.db.QueryRow(ctx, updateDependencyType, arg.Type, arg.ID)
	var i TaskDependency
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.DependsOnTaskID,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const validateLink = `-- name: ValidateLink :one
SELECT
	t.id AS task_id,
	t.title AS task_title,
	t.start_date AS task_start_date,
	t.end_date AS task_end_date,
	t.process_id AS task_process_id,
	(t.parent_id IS NULL)::bool AS task_is_top,
	COALESCE(p.id, 0) AS pred_id,
	COALESCE(p.title, '') AS pred_title,
	COALESCE(p.start_date, '0001-01-01') AS pred_start_date,
	COALESCE(p.end_date, '0001-01-01') AS pred_end_date,
	COALESCE(p.process_id, 0) AS pred_process_id,
	COALESCE(p.parent_id IS NULL, true)::bool AS pred_is_top
FROM tasks t
LEFT JOIN tasks p ON p.id = $1::bigint
WHERE t.id = $2::bigint
`

type ValidateLinkParams struct {
	DependsOnTaskID int64 `json:"depends_on_task_id"`
	TaskID          int64 `json:"task_id"`
}

type ValidateLinkRow struct {
	TaskID        int64     `json:"task_id"`
	TaskTitle     string    `json:"task_title"`
	TaskStartDate date.Date `json:"task_start_date"`
	TaskEndDate   date.Date `json:"task_end_date"`
	TaskProcessID int64     `json:"task_process_id"`
	TaskIsTop     bool      `json:"task_is_top"`
	PredID        int64     `json:"pred_id"`
	PredTitle     string    `json:"pred_title"`
	PredStartDate date.Date `json:"pred_start_date"`
	PredEndDate   date.Date `json:"pred_end_date"`
	PredProcessID int64     `json:"pred_process_id"`
	PredIsTop     bool      `json:"pred_is_top"`
}

// Both endpoints of a candidate dependency (the dependent task keyed by
// task_id, the predecessor by depends_on_task_id via LEFT JOIN — pred_id 0
// means the predecessor is missing). Carries the dates and the parent/process
// info so the service can enforce "same process + top-level only" and the
// candidate-edge date check in one round trip.
func (q *Queries) ValidateLink(ctx context.Context, arg ValidateLinkParams) (ValidateLinkRow, error) {
	row := q.db.QueryRow(ctx, validateLink, arg.DependsOnTaskID, arg.TaskID)
	var i ValidateLinkRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskTitle,
		&i.TaskStartDate,
		&i.TaskEndDate,
		&i.TaskProcessID,
		&i.TaskIsTop,
		&i.PredID,
		&i.PredTitle,
		&i.PredStartDate,
		&i.PredEndDate,
		&i.PredProcessID,
		&i.PredIsTop,
	)
	return i, err
}
