// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type TaskDependency struct {
	ID              int64     `json:"id"`
	TaskID          int64     `json:"task_id"`
	DependsOnTaskID int64     `json:"depends_on_task_id"`
	Type            string    `json:"type"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}
