// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID              int64          `json:"id"`
	LastName        string         `json:"last_name"`
	FirstName       string         `json:"first_name"`
	MiddleName      sql.NullString `json:"middle_name"`
	Preset          sql.NullString `json:"preset"`
	Username        string         `json:"username"`
	PasswordHash    string         `json:"password_hash"`
	ManagerID       pgtype.Int8    `json:"manager_id"`
	Position        string         `json:"position"`
	HireDate        pgtype.Date    `json:"hire_date"`
	TerminationDate pgtype.Date    `json:"termination_date"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type UserState struct {
	ID        int64     `json:"id"`
	UserID    int64     `json:"user_id"`
	StateID   int64     `json:"state_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
