// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/Koshsky/erp-backend/internal/auth/delivery"
	service2 "github.com/Koshsky/erp-backend/internal/auth/service"
	"github.com/Koshsky/erp-backend/internal/config"
	"github.com/Koshsky/erp-backend/internal/database"
	"github.com/Koshsky/erp-backend/internal/logger"
	"github.com/Koshsky/erp-backend/internal/middleware/auth"
	"github.com/Koshsky/erp-backend/internal/middleware/rbac"
	delivery2 "github.com/Koshsky/erp-backend/internal/planning/delivery"
	repository2 "github.com/Koshsky/erp-backend/internal/planning/repository"
	service3 "github.com/Koshsky/erp-backend/internal/planning/service"
	"github.com/Koshsky/erp-backend/internal/policies"
	delivery8 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/delivery"
	repository6 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/repository"
	service8 "github.com/Koshsky/erp-backend/internal/project_mgmt/assignment/service"
	delivery7 "github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/delivery"
	"github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/repository"
	service7 "github.com/Koshsky/erp-backend/internal/project_mgmt/milestone/service"
	delivery6 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/delivery"
	repository5 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/repository"
	service6 "github.com/Koshsky/erp-backend/internal/project_mgmt/process/service"
	delivery5 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/delivery"
	repository4 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/repository"
	service5 "github.com/Koshsky/erp-backend/internal/project_mgmt/project/service"
	delivery4 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/delivery"
	repository3 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/repository"
	service4 "github.com/Koshsky/erp-backend/internal/project_mgmt/task/service"
	"github.com/Koshsky/erp-backend/internal/security/jwt"
	delivery12 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/delivery"
	repository10 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/repository"
	service12 "github.com/Koshsky/erp-backend/internal/timesheet/calendar/service"
	delivery11 "github.com/Koshsky/erp-backend/internal/timesheet/employee/delivery"
	repository8 "github.com/Koshsky/erp-backend/internal/timesheet/employee/repository"
	service11 "github.com/Koshsky/erp-backend/internal/timesheet/employee/service"
	delivery9 "github.com/Koshsky/erp-backend/internal/timesheet/resource/delivery"
	repository7 "github.com/Koshsky/erp-backend/internal/timesheet/resource/repository"
	service9 "github.com/Koshsky/erp-backend/internal/timesheet/resource/service"
	delivery10 "github.com/Koshsky/erp-backend/internal/timesheet/state/delivery"
	repository9 "github.com/Koshsky/erp-backend/internal/timesheet/state/repository"
	service10 "github.com/Koshsky/erp-backend/internal/timesheet/state/service"
	delivery3 "github.com/Koshsky/erp-backend/internal/user/delivery"
	"github.com/Koshsky/erp-backend/internal/user/repository"
	"github.com/Koshsky/erp-backend/internal/user/service"
)

// Injectors from wire.go:

// InitializeApp builds the whole application dependency graph.
func InitializeApp() (*App, error) {
	configConfig, err := config.ProvideConfig()
	if err != nil {
		return nil, err
	}
	slogLogger, err := logger.ProvideLogger(configConfig)
	if err != nil {
		return nil, err
	}
	postgresConfig := config.ProvidePostgresConfig(configConfig)
	pool, err := database.ProvidePostgresDB(postgresConfig, slogLogger)
	if err != nil {
		return nil, err
	}
	jwtConfig := config.ProvideJWTConfig(configConfig)
	jwtService := jwt.ProvideJWTService(jwtConfig)
	middleware := auth.ProvideAuthMiddleware(slogLogger, jwtService)
	userRepository := repository.ProvideUserRepository(slogLogger, pool)
	userService := service.ProvideUserService(slogLogger, userRepository)
	authService := service2.ProvideAuthService(userService, jwtService)
	authHandler := delivery.ProvideAuthHandler(slogLogger, authService)
	routeRegistrar := ProvideAuthHandler(authHandler)
	planningRepository := repository2.ProvidePlanningRepository(slogLogger, pool)
	planningService := service3.ProvidePlanningService(slogLogger, planningRepository)
	planningHandler := delivery2.ProvidePlanningHandler(slogLogger, planningService)
	userHandler := delivery3.ProvideUserHandler(slogLogger, userService)
	taskRepository := repository3.ProvideTaskRepository(slogLogger, pool)
	taskService := service4.ProvideTaskService(slogLogger, taskRepository)
	projectRepository := repository4.ProvideProjectRepository(slogLogger, pool)
	processRepository := repository5.ProvideProcessRepository(slogLogger, pool)
	milestoneRepository := postgres.ProvideMilestoneRepository(slogLogger, pool)
	assignmentRepository := repository6.ProvideAssignmentRepository(slogLogger, pool)
	resourceRepository := repository7.ProvideResourceRepository(slogLogger, pool)
	employeeRepository := repository8.ProvideEmployeeRepository(slogLogger, pool)
	data := ProvideRBACData(projectRepository, processRepository, taskRepository, milestoneRepository, assignmentRepository, resourceRepository, employeeRepository)
	v := policies.ProvideAll()
	rbacMiddleware := rbac.ProvideMiddleware(slogLogger, data, v)
	taskHandler := delivery4.ProvideTaskHandler(slogLogger, taskService, rbacMiddleware)
	projectService := service5.ProvideProjectService(slogLogger, projectRepository)
	projectHandler := delivery5.ProvideProjectHandler(slogLogger, projectService, rbacMiddleware)
	processService := service6.ProvideProcessService(slogLogger, processRepository)
	processHandler := delivery6.ProvideProcessHandler(slogLogger, processService, rbacMiddleware)
	milestoneService := service7.ProvideMilestoneService(slogLogger, milestoneRepository)
	milestoneHandler := delivery7.ProvideMilestoneHandler(slogLogger, milestoneService, rbacMiddleware)
	assignmentService := service8.ProvideAssignmentService(slogLogger, assignmentRepository)
	assignmentHandler := delivery8.ProvideAssignmentHandler(slogLogger, assignmentService, rbacMiddleware)
	resourceService := service9.ProvideResourceService(slogLogger, resourceRepository)
	resourceHandler := delivery9.ProvideResourceHandler(slogLogger, resourceService, rbacMiddleware)
	stateRepository := repository9.ProvideStateRepository(slogLogger, pool)
	stateService := service10.ProvideStateService(slogLogger, stateRepository)
	stateHandler := delivery10.ProvideStateHandler(slogLogger, stateService, rbacMiddleware)
	employeeService := service11.ProvideEmployeeService(slogLogger, employeeRepository)
	employeeHandler := delivery11.ProvideEmployeeHandler(slogLogger, employeeService, rbacMiddleware)
	calendarRepository := repository10.ProvideCalendarRepository(slogLogger, pool)
	calendarService := service12.ProvideCalendarService(slogLogger, calendarRepository)
	calendarHandler := delivery12.ProvideCalendarHandler(slogLogger, calendarService, rbacMiddleware)
	protectedHandlers := ProvideProtectedHandlers(planningHandler, userHandler, taskHandler, projectHandler, processHandler, milestoneHandler, assignmentHandler, resourceHandler, stateHandler, employeeHandler, calendarHandler)
	app, err := New(configConfig, slogLogger, pool, middleware, routeRegistrar, protectedHandlers)
	if err != nil {
		return nil, err
	}
	return app, nil
}
