// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: idempotency.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE idempotency_keys
SET response_status = $1::int,
    response_body   = $2::jsonb
WHERE key = $3
	AND user_id = $4::bigint
	AND method = $5
	AND path = $6
`

type CompleteIdempotencyKeyParams struct {
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
	Key            string          `json:"key"`
	UserID         int64           `json:"user_id"`
	Method         string          `json:"method"`
	Path           string          `json:"path"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Key,
		arg.UserID,
		arg.Method,
		arg.Path,
	)
	return err
}

const createIdempotencyKey = `-- name: CreateIdempotencyKey :one
INSERT INTO idempotency_keys (key, user_id, method, path, expires_at)
VALUES ($1, $2::bigint, $3, $4, $5::timestamptz)
ON CONFLICT (key, user_id, method, path) DO NOTHING
RETURNING key, user_id, method, path, response_status, response_body, created_at, expires_at
`

type CreateIdempotencyKeyParams struct {
	Key       string    `json:"key"`
	UserID    int64     `json:"user_id"`
	Method    string    `json:"method"`
	Path      string    `json:"path"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateIdempotencyKey(ctx context.Context, arg CreateIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, createIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Method,
		arg.Path,
		arg.ExpiresAt,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :exec
DELETE FROM idempotency_keys
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys)
	return err
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_keys
WHERE key = $1
	AND user_id = $2::bigint
	AND method = $3
	AND path = $4
`

type DeleteIdempotencyKeyParams struct {
	Key    string `json:"key"`
	UserID int64  `json:"user_id"`
	Method string `json:"method"`
	Path   string `json:"path"`
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Method,
		arg.Path,
	)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, user_id, method, path, response_status, response_body, created_at, expires_at
FROM idempotency_keys
WHERE key = $1
	AND user_id = $2::bigint
	AND method = $3
	AND path = $4
`

type GetIdempotencyKeyParams struct {
	Key    string `json:"key"`
	UserID int64  `json:"user_id"`
	Method string `json:"method"`
	Path   string `json:"path"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey,
		arg.Key,
		arg.UserID,
		arg.Method,
		arg.Path,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
