// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"encoding/json"
	"time"
)

type IdempotencyKey struct {
	Key            string          `json:"key"`
	UserID         int64           `json:"user_id"`
	Method         string          `json:"method"`
	Path           string          `json:"path"`
	ResponseStatus int32           `json:"response_status"`
	ResponseBody   json.RawMessage `json:"response_body"`
	CreatedAt      time.Time       `json:"created_at"`
	ExpiresAt      time.Time       `json:"expires_at"`
}
