// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"
)

const canUserCreateTask = `-- name: CanUserCreateTask :one
SELECT EXISTS (
    SELECT 1 FROM processes p
    WHERE p.id = $1::bigint
	  AND p.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_create
`

type CanUserCreateTaskParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateTask(ctx context.Context, arg CanUserCreateTaskParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateTask, arg.ProcessID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserDeleteTask = `-- name: CanUserDeleteTask :one
SELECT EXISTS (
    SELECT 1 FROM tasks t
    JOIN processes p ON t.process_id = p.id
    WHERE t.id = $1::bigint
	  AND t.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserDeleteTaskParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CanUserDeleteTask(ctx context.Context, arg CanUserDeleteTaskParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserDeleteTask, arg.TaskID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const canUserUpdateTask = `-- name: CanUserUpdateTask :one
SELECT EXISTS (
    SELECT 1 FROM tasks t
    JOIN processes p ON t.process_id = p.id
    WHERE t.id = $1::bigint
	  AND t.deleted_at is NULL
      AND p.owner_id = $2::bigint
) AS can_manage
`

type CanUserUpdateTaskParams struct {
	TaskID int64 `json:"task_id"`
	UserID int64 `json:"user_id"`
}

func (q *Queries) CanUserUpdateTask(ctx context.Context, arg CanUserUpdateTaskParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserUpdateTask, arg.TaskID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (process_id, title, start_date, end_date)
VALUES ($1, $2, $3, $4)
RETURNING id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProcessID int64     `json:"process_id"`
	Title     string    `json:"title"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProcessID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const findTask = `-- name: FindTask :one
SELECT id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) FindTask(ctx context.Context, resourceID int64) (Task, error) {
	row := q.db.QueryRow(ctx, findTask, resourceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many

SELECT id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
ORDER BY id ASC
`

// TODO: write CanUserViewTask
func (q *Queries) ListTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
	process_id = $1,
	title = $2,
	start_date = $3,
	end_date = $4,
	updated_at = NOW()
WHERE id = $5
	AND deleted_at IS NULL
RETURNING id, process_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ProcessID int64     `json:"process_id"`
	Title     string    `json:"title"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	TaskID    int64     `json:"task_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ProcessID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
