// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: tasks.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*)
FROM tasks t
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE t.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint)) OR
    ($1::text = 'own' AND t.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR t.owner_id = $3::bigint OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
`

type CountTasksParams struct {
	ScopeView string `json:"scope_view"`
	UserID    int64  `json:"user_id"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountTasks(ctx context.Context, arg CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.ScopeView, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (process_id, owner_id, title, start_date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, process_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateTaskParams struct {
	ProcessID int64       `json:"process_id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProcessID,
		arg.OwnerID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
UPDATE tasks
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteTask(ctx context.Context, taskID int64) error {
	_, err := q.db.Exec(ctx, deleteTask, taskID)
	return err
}

const findTask = `-- name: FindTask :one
SELECT id, process_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM tasks
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) FindTask(ctx context.Context, resourceID int64) (Task, error) {
	row := q.db.QueryRow(ctx, findTask, resourceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTasks = `-- name: ListTasks :many
SELECT t.id, t.process_id, t.owner_id, t.title, t.start_date, t.end_date, t.created_at, t.updated_at, t.deleted_at
FROM tasks t
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE t.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint)) OR
    ($1::text = 'own' AND t.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR t.owner_id = $3::bigint OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
ORDER BY t.id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListTasksParams struct {
	ScopeView  string `json:"scope_view"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

func (q *Queries) ListTasks(ctx context.Context, arg ListTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.ScopeView,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.OwnerID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(pr.owner_id, 0)::bigint AS project_owner,
       COALESCE(p.owner_id, 0)::bigint  AS process_owner
FROM tasks t
JOIN processes p ON p.id = t.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE t.id = $1::bigint
	AND t.deleted_at IS NULL
	AND p.deleted_at IS NULL
	AND pr.deleted_at IS NULL
`

type OwnerChainRow struct {
	ProjectOwner int64 `json:"project_owner"`
	ProcessOwner int64 `json:"process_owner"`
}

func (q *Queries) OwnerChain(ctx context.Context, id int64) (OwnerChainRow, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var i OwnerChainRow
	err := row.Scan(&i.ProjectOwner, &i.ProcessOwner)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
	process_id = $1,
	owner_id = $2,
	title = $3,
	start_date = $4,
	end_date = $5,
	updated_at = NOW()
WHERE id = $6
	AND deleted_at IS NULL
RETURNING id, process_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateTaskParams struct {
	ProcessID int64       `json:"process_id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	TaskID    int64       `json:"task_id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ProcessID,
		arg.OwnerID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.TaskID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
