// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CanUserCreateTask(ctx context.Context, arg CanUserCreateTaskParams) (bool, error)
	CanUserDeleteTask(ctx context.Context, arg CanUserDeleteTaskParams) (bool, error)
	CanUserUpdateTask(ctx context.Context, arg CanUserUpdateTaskParams) (bool, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, taskID int64) error
	// TODO: write CanUserViewTask
	GetTask(ctx context.Context, resourceID int64) (Task, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
