// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: policies.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveRoles = `-- name: ListActiveRoles :many
SELECT id, name, description
FROM rbac_roles
WHERE deleted_at IS NULL
ORDER BY name
`

type ListActiveRolesRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) ListActiveRoles(ctx context.Context) ([]ListActiveRolesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRolesRow{}
	for rows.Next() {
		var i ListActiveRolesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRoutePolicies = `-- name: ListActiveRoutePolicies :many
SELECT name, kind, params, active, updated_by, updated_at
FROM rbac_route_policies
WHERE deleted_at IS NULL AND active = TRUE
`

type ListActiveRoutePoliciesRow struct {
	Name      string          `json:"name"`
	Kind      string          `json:"kind"`
	Params    json.RawMessage `json:"params"`
	Active    bool            `json:"active"`
	UpdatedBy pgtype.Int8     `json:"updated_by"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) ListActiveRoutePolicies(ctx context.Context) ([]ListActiveRoutePoliciesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRoutePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRoutePoliciesRow{}
	for rows.Next() {
		var i ListActiveRoutePoliciesRow
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.Params,
			&i.Active,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRules = `-- name: ListActiveRules :many
SELECT id, role, resource, action, scope, updated_by, updated_at
FROM rbac_role_rules
WHERE deleted_at IS NULL
`

type ListActiveRulesRow struct {
	ID        int64       `json:"id"`
	Role      string      `json:"role"`
	Resource  string      `json:"resource"`
	Action    string      `json:"action"`
	Scope     string      `json:"scope"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) ListActiveRules(ctx context.Context) ([]ListActiveRulesRow, error) {
	rows, err := q.db.Query(ctx, listActiveRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRulesRow{}
	for rows.Next() {
		var i ListActiveRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Resource,
			&i.Action,
			&i.Scope,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAllRoutePolicies = `-- name: SoftDeleteAllRoutePolicies :exec
UPDATE rbac_route_policies
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllRoutePolicies(ctx context.Context) error {
	_, err := q.db.Exec(ctx, softDeleteAllRoutePolicies)
	return err
}

const softDeleteAllRules = `-- name: SoftDeleteAllRules :exec
UPDATE rbac_role_rules
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
`

func (q *Queries) SoftDeleteAllRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, softDeleteAllRules)
	return err
}

const softDeleteRoutePolicy = `-- name: SoftDeleteRoutePolicy :exec
UPDATE rbac_route_policies
SET deleted_at = NOW(), updated_at = NOW()
WHERE name = $1::text AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRoutePolicy(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, softDeleteRoutePolicy, name)
	return err
}

const softDeleteRule = `-- name: SoftDeleteRule :exec
UPDATE rbac_role_rules
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1::bigint AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRule(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteRule, id)
	return err
}

const upsertRoutePolicy = `-- name: UpsertRoutePolicy :one
INSERT INTO rbac_route_policies (name, kind, params, active, updated_by)
VALUES ($1::text, $2::text, $3, $4, $5)
ON CONFLICT (name) DO UPDATE
SET kind = EXCLUDED.kind,
    params = EXCLUDED.params,
    active = EXCLUDED.active,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING name, kind, params, active, updated_by, updated_at
`

type UpsertRoutePolicyParams struct {
	Name      string          `json:"name"`
	Kind      string          `json:"kind"`
	Params    json.RawMessage `json:"params"`
	Active    bool            `json:"active"`
	UpdatedBy pgtype.Int8     `json:"updated_by"`
}

type UpsertRoutePolicyRow struct {
	Name      string          `json:"name"`
	Kind      string          `json:"kind"`
	Params    json.RawMessage `json:"params"`
	Active    bool            `json:"active"`
	UpdatedBy pgtype.Int8     `json:"updated_by"`
	UpdatedAt time.Time       `json:"updated_at"`
}

func (q *Queries) UpsertRoutePolicy(ctx context.Context, arg UpsertRoutePolicyParams) (UpsertRoutePolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertRoutePolicy,
		arg.Name,
		arg.Kind,
		arg.Params,
		arg.Active,
		arg.UpdatedBy,
	)
	var i UpsertRoutePolicyRow
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Params,
		&i.Active,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRule = `-- name: UpsertRule :one
INSERT INTO rbac_role_rules (role, resource, action, scope, updated_by)
VALUES ($1::text, $2::text, $3::text, $4::text, $5)
ON CONFLICT (role, resource, action) DO UPDATE
SET scope = EXCLUDED.scope,
    updated_by = EXCLUDED.updated_by,
    updated_at = NOW()
RETURNING id, role, resource, action, scope, updated_by, updated_at
`

type UpsertRuleParams struct {
	Role      string      `json:"role"`
	Resource  string      `json:"resource"`
	Action    string      `json:"action"`
	Scope     string      `json:"scope"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
}

type UpsertRuleRow struct {
	ID        int64       `json:"id"`
	Role      string      `json:"role"`
	Resource  string      `json:"resource"`
	Action    string      `json:"action"`
	Scope     string      `json:"scope"`
	UpdatedBy pgtype.Int8 `json:"updated_by"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) UpsertRule(ctx context.Context, arg UpsertRuleParams) (UpsertRuleRow, error) {
	row := q.db.QueryRow(ctx, upsertRule,
		arg.Role,
		arg.Resource,
		arg.Action,
		arg.Scope,
		arg.UpdatedBy,
	)
	var i UpsertRuleRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Resource,
		&i.Action,
		&i.Scope,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
