// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Process struct {
	ID        int64          `json:"id"`
	ProjectID int64          `json:"project_id"`
	OwnerID   pgtype.Int8    `json:"owner_id"`
	Title     string         `json:"title"`
	Color     sql.NullString `json:"color"`
	StartDate time.Time      `json:"start_date"`
	EndDate   time.Time      `json:"end_date"`
	SortOrder int32          `json:"sort_order"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
