// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: processes.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProcesses = `-- name: CountProcesses :one
SELECT COUNT(*)
FROM processes p
JOIN projects pr ON pr.id = p.project_id
WHERE p.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND pr.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint)) OR
    ($1::text = 'own' AND p.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
`

type CountProcessesParams struct {
	ScopeView string `json:"scope_view"`
	UserID    int64  `json:"user_id"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountProcesses(ctx context.Context, arg CountProcessesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProcesses, arg.ScopeView, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (project_id, title, start_date, end_date, owner_id, sort_order)
VALUES (
	$1::bigint,
	$2::text,
	$3::date,
	$4::date,
	$5,
	-- New process goes to the end of its project group.
	(SELECT COALESCE(MAX(sort_order), 0) + 1 FROM processes WHERE project_id = $1::bigint)
)
RETURNING id, project_id, owner_id, title, start_date, end_date, sort_order, created_at, updated_at, deleted_at
`

type CreateProcessParams struct {
	ProjectID int64       `json:"project_id"`
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, createProcess,
		arg.ProjectID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :exec
UPDATE processes
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) DeleteProcess(ctx context.Context, processID int64) error {
	_, err := q.db.Exec(ctx, deleteProcess, processID)
	return err
}

const findProcess = `-- name: FindProcess :one
SELECT id, project_id, owner_id, title, start_date, end_date, sort_order, created_at, updated_at, deleted_at
FROM processes
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) FindProcess(ctx context.Context, id int64) (Process, error) {
	row := q.db.QueryRow(ctx, findProcess, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProcessIdsByProject = `-- name: ListProcessIdsByProject :many
SELECT id
FROM processes
WHERE project_id = $1::bigint
	AND deleted_at IS NULL
ORDER BY sort_order ASC, id ASC
`

// Active process ids of a project — to validate a reorder request covers the
// whole group.
func (q *Queries) ListProcessIdsByProject(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProcessIdsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcesss = `-- name: ListProcesss :many
SELECT p.id, p.project_id, p.owner_id, p.title, p.start_date, p.end_date, p.sort_order, p.created_at, p.updated_at, p.deleted_at
FROM processes p
JOIN projects pr ON pr.id = p.project_id
WHERE p.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND pr.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint)) OR
    ($1::text = 'own' AND p.owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
ORDER BY p.sort_order ASC, p.id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListProcesssParams struct {
	ScopeView  string `json:"scope_view"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

func (q *Queries) ListProcesss(ctx context.Context, arg ListProcesssParams) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcesss,
		arg.ScopeView,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(pr.owner_id, 0)::bigint AS project_owner,
       COALESCE(p.owner_id, 0)::bigint  AS process_owner
FROM processes p
JOIN projects pr ON pr.id = p.project_id
WHERE p.id = $1::bigint
	AND p.deleted_at IS NULL
	AND pr.deleted_at IS NULL
`

type OwnerChainRow struct {
	ProjectOwner int64 `json:"project_owner"`
	ProcessOwner int64 `json:"process_owner"`
}

func (q *Queries) OwnerChain(ctx context.Context, id int64) (OwnerChainRow, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var i OwnerChainRow
	err := row.Scan(&i.ProjectOwner, &i.ProcessOwner)
	return i, err
}

const reorderProcesses = `-- name: ReorderProcesses :exec
UPDATE processes p
SET sort_order = x.ord, updated_at = NOW()
FROM unnest($1::bigint[]) WITH ORDINALITY AS x(id, ord)
WHERE p.id = x.id AND p.deleted_at IS NULL
`

// Rewrites the order of the given process ids in one statement (transactional
// guarantee comes from a single UPDATE: the caller sends the whole group).
func (q *Queries) ReorderProcesses(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, reorderProcesses, ids)
	return err
}

const updateProcess = `-- name: UpdateProcess :one
UPDATE processes
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	project_id = COALESCE($4, project_id),
	owner_id = COALESCE($5, owner_id),
	updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $6::bigint
RETURNING id, project_id, owner_id, title, start_date, end_date, sort_order, created_at, updated_at, deleted_at
`

type UpdateProcessParams struct {
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	ProjectID int64       `json:"project_id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	ProcessID int64       `json:"process_id"`
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, updateProcess,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.ProjectID,
		arg.OwnerID,
		arg.ProcessID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
