// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: processes.sql

package sqlc

import (
	"context"
	"time"
)

const canUserCreateProcess = `-- name: CanUserCreateProcess :one
SELECT EXISTS(
	SELECT 1 FROM projects
	WHERE id = $1::bigint
		AND deleted_at IS NULL
		AND owner_id = $2::bigint
) AS can_create
`

type CanUserCreateProcessParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserCreateProcess(ctx context.Context, arg CanUserCreateProcessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserCreateProcess, arg.ProjectID, arg.UserID)
	var can_create bool
	err := row.Scan(&can_create)
	return can_create, err
}

const canUserDeleteProcess = `-- name: CanUserDeleteProcess :one
SELECT EXISTS (
    SELECT 1 FROM processes p
    JOIN projects pr ON pr.id = p.project_id
    WHERE p.id = $1::bigint
      AND p.deleted_at IS NULL
      AND pr.owner_id = $2::bigint
) AS can_manage
`

type CanUserDeleteProcessParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserDeleteProcess(ctx context.Context, arg CanUserDeleteProcessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserDeleteProcess, arg.ProcessID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const canUserUpdateProcess = `-- name: CanUserUpdateProcess :one
SELECT EXISTS (
    SELECT 1 FROM processes p
    JOIN projects pr ON pr.id = p.project_id
    WHERE p.id = $1::bigint
      AND p.deleted_at IS NULL
      AND pr.owner_id = $2::bigint
) AS can_manage
`

type CanUserUpdateProcessParams struct {
	ProcessID int64 `json:"process_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) CanUserUpdateProcess(ctx context.Context, arg CanUserUpdateProcessParams) (bool, error) {
	row := q.db.QueryRow(ctx, canUserUpdateProcess, arg.ProcessID, arg.UserID)
	var can_manage bool
	err := row.Scan(&can_manage)
	return can_manage, err
}

const createProcess = `-- name: CreateProcess :one
INSERT INTO processes (project_id, title, start_date, end_date, owner_id)
VALUES (
	$1::bigint,
	$2::text,
	$3::date,
	$4::date,
	$5::bigint
)
RETURNING id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type CreateProcessParams struct {
	ProjectID int64     `json:"project_id"`
	Title     string    `json:"title"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	OwnerID   int64     `json:"owner_id"`
}

func (q *Queries) CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, createProcess,
		arg.ProjectID,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProcess = `-- name: DeleteProcess :exec
UPDATE processes
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) DeleteProcess(ctx context.Context, processID int64) error {
	_, err := q.db.Exec(ctx, deleteProcess, processID)
	return err
}

const getProcess = `-- name: GetProcess :one
SELECT id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM processes
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) GetProcess(ctx context.Context, id int64) (Process, error) {
	row := q.db.QueryRow(ctx, getProcess, id)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProcesss = `-- name: ListProcesss :many

SELECT id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
FROM processes
WHERE deleted_at IS NULL
ORDER BY id ASC
`

// TODO: write CanUserViewProcess
func (q *Queries) ListProcesss(ctx context.Context) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcesss)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProcess = `-- name: UpdateProcess :one
UPDATE processes
SET
	title = $1,
	start_date = $2,
	end_date = $3,
	owner_id = COALESCE($4, owner_id),
	updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $5::bigint
RETURNING id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at
`

type UpdateProcessParams struct {
	Title     string    `json:"title"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	OwnerID   int64     `json:"owner_id"`
	ProcessID int64     `json:"process_id"`
}

func (q *Queries) UpdateProcess(ctx context.Context, arg UpdateProcessParams) (Process, error) {
	row := q.db.QueryRow(ctx, updateProcess,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
		arg.ProcessID,
	)
	var i Process
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.OwnerID,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
