// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	CanUserCreateProcess(ctx context.Context, arg CanUserCreateProcessParams) (bool, error)
	CanUserDeleteProcess(ctx context.Context, arg CanUserDeleteProcessParams) (bool, error)
	CanUserUpdateProcess(ctx context.Context, arg CanUserUpdateProcessParams) (bool, error)
	CreateProcess(ctx context.Context, arg CreateProcessParams) (Process, error)
	DeleteProcess(ctx context.Context, processID int64) error
	// TODO: write CanUserViewProcess
	FindProcess(ctx context.Context, id int64) (Process, error)
	UpdateProcess(ctx context.Context, arg UpdateProcessParams) (Process, error)
}

var _ Querier = (*Queries)(nil)
