// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID         int64       `json:"id"`
	TaskID     int64       `json:"task_id"`
	ResourceID int64       `json:"resource_id"`
	Quantity   int32       `json:"quantity"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
	DeletedAt  **time.Time `json:"deleted_at"`
}

type Milestone struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	Title     string      `json:"title"`
	Content   string      `json:"content"`
	Date      time.Time   `json:"date"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt **time.Time `json:"deleted_at"`
}

type Process struct {
	ID        int64       `json:"id"`
	ProjectID int64       `json:"project_id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt **time.Time `json:"deleted_at"`
}

type Project struct {
	ID        int64       `json:"id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	Code      string      `json:"code"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	Priority  int32       `json:"priority"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt **time.Time `json:"deleted_at"`
}

type Resource struct {
	ID        int64       `json:"id"`
	Title     string      `json:"title"`
	Code      string      `json:"code"`
	Quantity  int32       `json:"quantity"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt **time.Time `json:"deleted_at"`
}

type Task struct {
	ID        int64       `json:"id"`
	ProcessID int64       `json:"process_id"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	Title     string      `json:"title"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
	DeletedAt **time.Time `json:"deleted_at"`
}

type User struct {
	ID           int64       `json:"id"`
	Name         string      `json:"name"`
	Role         string      `json:"role"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	ManagerID    pgtype.Int8 `json:"manager_id"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	DeletedAt    **time.Time `json:"deleted_at"`
}
