// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: projects.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)
FROM projects
WHERE deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'own' AND owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR owner_id = $3::bigint)
`

type CountProjectsParams struct {
	ScopeView string `json:"scope_view"`
	UserID    int64  `json:"user_id"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountProjects(ctx context.Context, arg CountProjectsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, arg.ScopeView, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (code, start_date, end_date, priority, owner_id)
VALUES (
  $1::text,
  $2::date,
  $3::date,
  $4::bigint,
  $5
)
ON CONFLICT (code) WHERE deleted_at IS NULL
DO NOTHING
RETURNING id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
`

type CreateProjectParams struct {
	Code      string      `json:"code"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	Priority  int64       `json:"priority"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
}

// Idempotent create by business key code: if an active code already exists
// we insert nothing; the calling code (repository) turns the conflict into 409.
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Code,
		arg.StartDate,
		arg.EndDate,
		arg.Priority,
		arg.OwnerID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) DeleteProject(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, deleteProject, projectID)
	return err
}

const findProject = `-- name: FindProject :one
SELECT id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
  AND id = $1::bigint
`

func (q *Queries) FindProject(ctx context.Context, projectID int64) (Project, error) {
	row := q.db.QueryRow(ctx, findProject, projectID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
FROM projects
WHERE deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'own' AND owner_id = $2::bigint)
  )
  AND ($3::bigint = 0 OR owner_id = $3::bigint)
ORDER BY id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListProjectsParams struct {
	ScopeView  string `json:"scope_view"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.ScopeView,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(owner_id, 0)::bigint AS owner_id
FROM projects
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) OwnerChain(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var owner_id int64
	err := row.Scan(&owner_id)
	return owner_id, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET
	code = $1,
	priority = $2::bigint,
	start_date = $3,
	end_date = $4,
  owner_id = $5,
	updated_at = NOW()
WHERE deleted_at IS NULL
	AND id = $6::bigint
RETURNING id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at
`

type UpdateProjectParams struct {
	Code      string      `json:"code"`
	Priority  int64       `json:"priority"`
	StartDate time.Time   `json:"start_date"`
	EndDate   time.Time   `json:"end_date"`
	OwnerID   pgtype.Int8 `json:"owner_id"`
	ProjectID int64       `json:"project_id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Code,
		arg.Priority,
		arg.StartDate,
		arg.EndDate,
		arg.OwnerID,
		arg.ProjectID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Code,
		&i.StartDate,
		&i.EndDate,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
