// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO task_comments (task_id, author_id, parent_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, task_id, author_id, parent_id, content, created_at, updated_at, deleted_at
`

type CreateCommentParams struct {
	TaskID   int64       `json:"task_id"`
	AuthorID int64       `json:"author_id"`
	ParentID pgtype.Int8 `json:"parent_id"`
	Content  string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (TaskComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TaskID,
		arg.AuthorID,
		arg.ParentID,
		arg.Content,
	)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE task_comments
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, commentID int64) error {
	_, err := q.db.Exec(ctx, deleteComment, commentID)
	return err
}

const findComment = `-- name: FindComment :one
SELECT id, task_id, author_id, parent_id, content, created_at, updated_at, deleted_at
FROM task_comments
WHERE id = $1::bigint
	AND deleted_at IS NULL
`

func (q *Queries) FindComment(ctx context.Context, commentID int64) (TaskComment, error) {
	row := q.db.QueryRow(ctx, findComment, commentID)
	var i TaskComment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorID,
		&i.ParentID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT id, task_id, author_id, parent_id, content, created_at, updated_at, deleted_at
FROM task_comments
WHERE task_id = $1::bigint
	AND deleted_at IS NULL
ORDER BY created_at ASC, id ASC
`

func (q *Queries) ListComments(ctx context.Context, taskID int64) ([]TaskComment, error) {
	rows, err := q.db.Query(ctx, listComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskComment{}
	for rows.Next() {
		var i TaskComment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorID,
			&i.ParentID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(pr.owner_id, 0)::bigint AS project_owner,
       COALESCE(p.owner_id, 0)::bigint  AS process_owner,
       tc.author_id                      AS author
FROM task_comments tc
JOIN tasks t ON t.id = tc.task_id AND t.deleted_at IS NULL
JOIN processes p ON p.id = t.process_id AND p.deleted_at IS NULL
JOIN projects pr ON pr.id = p.project_id AND pr.deleted_at IS NULL
WHERE tc.id = $1::bigint
	AND tc.deleted_at IS NULL
`

type OwnerChainRow struct {
	ProjectOwner int64 `json:"project_owner"`
	ProcessOwner int64 `json:"process_owner"`
	Author       int64 `json:"author"`
}

func (q *Queries) OwnerChain(ctx context.Context, id int64) (OwnerChainRow, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var i OwnerChainRow
	err := row.Scan(&i.ProjectOwner, &i.ProcessOwner, &i.Author)
	return i, err
}
