// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type TaskComment struct {
	ID        int64       `json:"id"`
	TaskID    int64       `json:"task_id"`
	AuthorID  int64       `json:"author_id"`
	ParentID  pgtype.Int8 `json:"parent_id"`
	Content   string      `json:"content"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
