// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employees.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (resource_id, name, manager_id, hire_date, termination_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, resource_id, name, manager_id, hire_date, termination_date, created_at, updated_at, deleted_at
`

type CreateEmployeeParams struct {
	ResourceID      int64       `json:"resource_id"`
	Name            string      `json:"name"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.ResourceID,
		arg.Name,
		arg.ManagerID,
		arg.HireDate,
		arg.TerminationDate,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Name,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
UPDATE employees
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteEmployee(ctx context.Context, employeeID int64) error {
	_, err := q.db.Exec(ctx, deleteEmployee, employeeID)
	return err
}

const findEmployee = `-- name: FindEmployee :one
SELECT e.id, e.resource_id, e.name, e.manager_id, e.hire_date, e.termination_date, e.created_at, e.updated_at, e.deleted_at, r.title AS resource_title
FROM employees e
JOIN resources r ON r.id = e.resource_id
WHERE e.id = $1::bigint
	AND e.deleted_at IS NULL
`

type FindEmployeeRow struct {
	ID              int64       `json:"id"`
	ResourceID      int64       `json:"resource_id"`
	Name            string      `json:"name"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DeletedAt       **time.Time `json:"deleted_at"`
	ResourceTitle   string      `json:"resource_title"`
}

func (q *Queries) FindEmployee(ctx context.Context, employeeID int64) (FindEmployeeRow, error) {
	row := q.db.QueryRow(ctx, findEmployee, employeeID)
	var i FindEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Name,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceTitle,
	)
	return i, err
}

const isResourceActive = `-- name: IsResourceActive :one
SELECT EXISTS(
	SELECT 1
	FROM resources
	WHERE id = $1::bigint
		AND deleted_at IS NULL
)
`

func (q *Queries) IsResourceActive(ctx context.Context, resourceID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isResourceActive, resourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listEmployees = `-- name: ListEmployees :many
SELECT e.id, e.resource_id, e.name, e.manager_id, e.hire_date, e.termination_date, e.created_at, e.updated_at, e.deleted_at, r.title AS resource_title
FROM employees e
JOIN resources r ON r.id = e.resource_id
WHERE e.deleted_at IS NULL
ORDER BY e.id ASC
`

type ListEmployeesRow struct {
	ID              int64       `json:"id"`
	ResourceID      int64       `json:"resource_id"`
	Name            string      `json:"name"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DeletedAt       **time.Time `json:"deleted_at"`
	ResourceTitle   string      `json:"resource_title"`
}

func (q *Queries) ListEmployees(ctx context.Context) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ResourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByResourceID = `-- name: ListEmployeesByResourceID :many
SELECT e.id, e.resource_id, e.name, e.manager_id, e.hire_date, e.termination_date, e.created_at, e.updated_at, e.deleted_at, r.title AS resource_title
FROM employees e
JOIN resources r ON r.id = e.resource_id
WHERE e.resource_id = $1::bigint
	AND e.deleted_at IS NULL
ORDER BY e.id ASC
`

type ListEmployeesByResourceIDRow struct {
	ID              int64       `json:"id"`
	ResourceID      int64       `json:"resource_id"`
	Name            string      `json:"name"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
	CreatedAt       time.Time   `json:"created_at"`
	UpdatedAt       time.Time   `json:"updated_at"`
	DeletedAt       **time.Time `json:"deleted_at"`
	ResourceTitle   string      `json:"resource_title"`
}

func (q *Queries) ListEmployeesByResourceID(ctx context.Context, resourceID int64) ([]ListEmployeesByResourceIDRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesByResourceID, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByResourceIDRow{}
	for rows.Next() {
		var i ListEmployeesByResourceIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.Name,
			&i.ManagerID,
			&i.HireDate,
			&i.TerminationDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ResourceTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmployee = `-- name: UpdateEmployee :one
UPDATE employees
SET
	name = $1,
	manager_id = $2,
	hire_date = $3,
	termination_date = $4,
	updated_at = NOW()
WHERE id = $5
	AND deleted_at IS NULL
RETURNING id, resource_id, name, manager_id, hire_date, termination_date, created_at, updated_at, deleted_at
`

type UpdateEmployeeParams struct {
	Name            string      `json:"name"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
	EmployeeID      int64       `json:"employee_id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, updateEmployee,
		arg.Name,
		arg.ManagerID,
		arg.HireDate,
		arg.TerminationDate,
		arg.EmployeeID,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.ResourceID,
		&i.Name,
		&i.ManagerID,
		&i.HireDate,
		&i.TerminationDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
