// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: employee_states.sql

package sqlc

import (
	"context"
	"time"
)

const deleteOverlapping = `-- name: DeleteOverlapping :exec
DELETE FROM employee_states
WHERE employee_id = $1::bigint
	AND end_date >= $2::date
	AND start_date <= $3::date
`

type DeleteOverlappingParams struct {
	EmployeeID int64     `json:"employee_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

func (q *Queries) DeleteOverlapping(ctx context.Context, arg DeleteOverlappingParams) error {
	_, err := q.db.Exec(ctx, deleteOverlapping, arg.EmployeeID, arg.StartDate, arg.EndDate)
	return err
}

const deleteOverlappingByState = `-- name: DeleteOverlappingByState :exec
DELETE FROM employee_states
WHERE employee_id = $1::bigint
	AND state_id = $2::bigint
	AND end_date >= $3::date
	AND start_date <= $4::date
`

type DeleteOverlappingByStateParams struct {
	EmployeeID int64     `json:"employee_id"`
	StateID    int64     `json:"state_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

func (q *Queries) DeleteOverlappingByState(ctx context.Context, arg DeleteOverlappingByStateParams) error {
	_, err := q.db.Exec(ctx, deleteOverlappingByState,
		arg.EmployeeID,
		arg.StateID,
		arg.StartDate,
		arg.EndDate,
	)
	return err
}

const insertStateRange = `-- name: InsertStateRange :one
INSERT INTO employee_states (employee_id, state_id, start_date, end_date)
VALUES ($1, $2, $3::date, $4::date)
RETURNING id, employee_id, state_id, start_date, end_date, created_at, updated_at
`

type InsertStateRangeParams struct {
	EmployeeID int64     `json:"employee_id"`
	StateID    int64     `json:"state_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

func (q *Queries) InsertStateRange(ctx context.Context, arg InsertStateRangeParams) (EmployeeState, error) {
	row := q.db.QueryRow(ctx, insertStateRange,
		arg.EmployeeID,
		arg.StateID,
		arg.StartDate,
		arg.EndDate,
	)
	var i EmployeeState
	err := row.Scan(
		&i.ID,
		&i.EmployeeID,
		&i.StateID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOverlappingStates = `-- name: ListOverlappingStates :many
SELECT es.id, es.employee_id, es.start_date, es.end_date, es.state_id
FROM employee_states es
WHERE es.employee_id = $1::bigint
	AND es.end_date >= $2::date
	AND es.start_date <= $3::date
ORDER BY es.start_date ASC
FOR UPDATE
`

type ListOverlappingStatesParams struct {
	EmployeeID int64     `json:"employee_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

type ListOverlappingStatesRow struct {
	ID         int64     `json:"id"`
	EmployeeID int64     `json:"employee_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
	StateID    int64     `json:"state_id"`
}

func (q *Queries) ListOverlappingStates(ctx context.Context, arg ListOverlappingStatesParams) ([]ListOverlappingStatesRow, error) {
	rows, err := q.db.Query(ctx, listOverlappingStates, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverlappingStatesRow{}
	for rows.Next() {
		var i ListOverlappingStatesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.StateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverlappingStatesByState = `-- name: ListOverlappingStatesByState :many
SELECT es.id, es.employee_id, es.start_date, es.end_date, es.state_id
FROM employee_states es
WHERE es.employee_id = $1::bigint
	AND es.state_id = $2::bigint
	AND es.end_date >= $3::date
	AND es.start_date <= $4::date
ORDER BY es.start_date ASC
FOR UPDATE
`

type ListOverlappingStatesByStateParams struct {
	EmployeeID int64     `json:"employee_id"`
	StateID    int64     `json:"state_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

type ListOverlappingStatesByStateRow struct {
	ID         int64     `json:"id"`
	EmployeeID int64     `json:"employee_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
	StateID    int64     `json:"state_id"`
}

func (q *Queries) ListOverlappingStatesByState(ctx context.Context, arg ListOverlappingStatesByStateParams) ([]ListOverlappingStatesByStateRow, error) {
	rows, err := q.db.Query(ctx, listOverlappingStatesByState,
		arg.EmployeeID,
		arg.StateID,
		arg.StartDate,
		arg.EndDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOverlappingStatesByStateRow{}
	for rows.Next() {
		var i ListOverlappingStatesByStateRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.StateID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatesByEmployeeRange = `-- name: ListStatesByEmployeeRange :many
SELECT es.id, es.employee_id, es.start_date, es.end_date, es.state_id,
	s.code AS state_code, s.name AS state_name, s.is_available
FROM employee_states es
JOIN states s ON s.id = es.state_id
WHERE es.employee_id = $1::bigint
	AND es.end_date >= $2::date
	AND es.start_date <= $3::date
ORDER BY es.start_date ASC
`

type ListStatesByEmployeeRangeParams struct {
	EmployeeID int64     `json:"employee_id"`
	StartDate  time.Time `json:"start_date"`
	EndDate    time.Time `json:"end_date"`
}

type ListStatesByEmployeeRangeRow struct {
	ID          int64     `json:"id"`
	EmployeeID  int64     `json:"employee_id"`
	StartDate   time.Time `json:"start_date"`
	EndDate     time.Time `json:"end_date"`
	StateID     int64     `json:"state_id"`
	StateCode   string    `json:"state_code"`
	StateName   string    `json:"state_name"`
	IsAvailable bool      `json:"is_available"`
}

func (q *Queries) ListStatesByEmployeeRange(ctx context.Context, arg ListStatesByEmployeeRangeParams) ([]ListStatesByEmployeeRangeRow, error) {
	rows, err := q.db.Query(ctx, listStatesByEmployeeRange, arg.EmployeeID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStatesByEmployeeRangeRow{}
	for rows.Next() {
		var i ListStatesByEmployeeRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.StartDate,
			&i.EndDate,
			&i.StateID,
			&i.StateCode,
			&i.StateName,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
