// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO refresh_sessions (user_id, token_hash, expires_at, replaced_by)
VALUES ($1::bigint, $2::text, $3, $4)
RETURNING id, user_id, token_hash, created_at, expires_at, revoked_at, COALESCE(replaced_by, 0)::bigint AS replaced_by
`

type CreateSessionParams struct {
	UserID     int64       `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	ExpiresAt  time.Time   `json:"expires_at"`
	ReplacedBy pgtype.Int8 `json:"replaced_by"`
}

type CreateSessionRow struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	CreatedAt  time.Time   `json:"created_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	RevokedAt  **time.Time `json:"revoked_at"`
	ReplacedBy int64       `json:"replaced_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.ReplacedBy,
	)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM refresh_sessions
WHERE expires_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, olderThan time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions, olderThan)
	return err
}

const findActiveSession = `-- name: FindActiveSession :one
SELECT id, user_id, token_hash, created_at, expires_at, revoked_at, COALESCE(replaced_by, 0)::bigint AS replaced_by
FROM refresh_sessions
WHERE token_hash = $1::text
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

type FindActiveSessionRow struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	CreatedAt  time.Time   `json:"created_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	RevokedAt  **time.Time `json:"revoked_at"`
	ReplacedBy int64       `json:"replaced_by"`
}

// Проверка: считается ли токен активным (revoked_at IS NULL AND expires_at > NOW()).
func (q *Queries) FindActiveSession(ctx context.Context, tokenHash string) (FindActiveSessionRow, error) {
	row := q.db.QueryRow(ctx, findActiveSession, tokenHash)
	var i FindActiveSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const findSessionByHash = `-- name: FindSessionByHash :one
SELECT id, user_id, token_hash, created_at, expires_at, revoked_at, COALESCE(replaced_by, 0)::bigint AS replaced_by
FROM refresh_sessions
WHERE token_hash = $1::text
LIMIT 1
`

type FindSessionByHashRow struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	TokenHash  string      `json:"token_hash"`
	CreatedAt  time.Time   `json:"created_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	RevokedAt  **time.Time `json:"revoked_at"`
	ReplacedBy int64       `json:"replaced_by"`
}

// Найти сессию по хэшу (включая отозванные/истёкшие — для детекта повторного использования).
func (q *Queries) FindSessionByHash(ctx context.Context, tokenHash string) (FindSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByHash, tokenHash)
	var i FindSessionByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE refresh_sessions
SET revoked_at = NOW()
WHERE user_id = $1::bigint
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE refresh_sessions
SET revoked_at = NOW()
WHERE id = $1::bigint
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}
