// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calendar.sql

package sqlc

import (
	"context"

	"github.com/Koshsky/erp-backend/pkg/date"
	"github.com/jackc/pgx/v5/pgtype"
)

const listEmployeesForCalendar = `-- name: ListEmployeesForCalendar :many
SELECT u.id, rm.resource_id, u.hire_date, u.termination_date
FROM resource_members rm
JOIN users u ON u.id = rm.user_id
WHERE (u.hire_date IS NULL OR u.hire_date <= $1::date)
    AND (u.termination_date IS NULL OR u.termination_date >= $2::date)
ORDER BY rm.resource_id ASC, u.id ASC
`

type ListEmployeesForCalendarParams struct {
	EndDate   date.Date `json:"end_date"`
	StartDate date.Date `json:"start_date"`
}

type ListEmployeesForCalendarRow struct {
	ID              int64       `json:"id"`
	ResourceID      int64       `json:"resource_id"`
	HireDate        pgtype.Date `json:"hire_date"`
	TerminationDate pgtype.Date `json:"termination_date"`
}

// Members that could be active within the [start_date, end_date] window
// (by hire_date/termination_date), without per-day expansion.
func (q *Queries) ListEmployeesForCalendar(ctx context.Context, arg ListEmployeesForCalendarParams) ([]ListEmployeesForCalendarRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesForCalendar, arg.EndDate, arg.StartDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesForCalendarRow{}
	for rows.Next() {
		var i ListEmployeesForCalendarRow
		if err := rows.Scan(
			&i.ID,
			&i.ResourceID,
			&i.HireDate,
			&i.TerminationDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, title, code, owner_id
FROM resources
WHERE (
    $1::boolean OR
    ($2::boolean AND owner_id = $3::bigint) OR
    $4::boolean
)
ORDER BY id ASC
`

type ListResourcesParams struct {
	ScAll  bool  `json:"sc_all"`
	ScSelf bool  `json:"sc_self"`
	UserID int64 `json:"user_id"`
	ScNone bool  `json:"sc_none"`
}

type ListResourcesRow struct {
	ID      int64  `json:"id"`
	Title   string `json:"title"`
	Code    string `json:"code"`
	OwnerID int64  `json:"owner_id"`
}

// Scoped by the caller's resource view zone (calendar.view): a process owner
// must not read capacity curves of resources outside its own scope. The route
// policy already gates the endpoint on resource.view; a caller whose zone
// resolves empty (no rule / none) gets every row — reference data must not be
// dropped then.
func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources,
		arg.ScAll,
		arg.ScSelf,
		arg.UserID,
		arg.ScNone,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnavailableRanges = `-- name: ListUnavailableRanges :many
SELECT rm.resource_id, es.start_date, es.end_date
FROM user_states es
JOIN resource_members rm ON rm.user_id = es.user_id
JOIN states s ON s.id = es.state_id
WHERE s.is_available = FALSE
    AND es.end_date >= $1::date
    AND es.start_date <= $2::date
ORDER BY rm.resource_id ASC, es.start_date ASC
`

type ListUnavailableRangesParams struct {
	StartDate date.Date `json:"start_date"`
	EndDate   date.Date `json:"end_date"`
}

type ListUnavailableRangesRow struct {
	ResourceID int64     `json:"resource_id"`
	StartDate  date.Date `json:"start_date"`
	EndDate    date.Date `json:"end_date"`
}

// Absence intervals (is_available = false) overlapping the window, without expansion.
func (q *Queries) ListUnavailableRanges(ctx context.Context, arg ListUnavailableRangesParams) ([]ListUnavailableRangesRow, error) {
	rows, err := q.db.Query(ctx, listUnavailableRanges, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnavailableRangesRow{}
	for rows.Next() {
		var i ListUnavailableRangesRow
		if err := rows.Scan(&i.ResourceID, &i.StartDate, &i.EndDate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
