// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: calendar.sql

package sqlc

import (
	"context"
	"time"
)

const listCalendarCapacity = `-- name: ListCalendarCapacity :many
SELECT r.id AS resource_id,
    g.date::date,
    COUNT(e.id)::bigint AS capacity
FROM resources r
CROSS JOIN generate_series($1::date, $2::date, INTERVAL '1 day') AS g(date)
LEFT JOIN employees e
    ON e.resource_id = r.id
    AND e.deleted_at IS NULL
    AND (e.hire_date IS NULL OR e.hire_date <= g.date)
    AND (e.termination_date IS NULL OR e.termination_date >= g.date)
WHERE r.deleted_at IS NULL
GROUP BY r.id, g.date::date
ORDER BY r.id ASC, g.date::date ASC
`

type ListCalendarCapacityParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type ListCalendarCapacityRow struct {
	ResourceID int64     `json:"resource_id"`
	GDate      time.Time `json:"g_date"`
	Capacity   int64     `json:"capacity"`
}

// По-дневная мощность категории: сколько сотрудников активно в каждый день диапазона.
func (q *Queries) ListCalendarCapacity(ctx context.Context, arg ListCalendarCapacityParams) ([]ListCalendarCapacityRow, error) {
	rows, err := q.db.Query(ctx, listCalendarCapacity, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarCapacityRow{}
	for rows.Next() {
		var i ListCalendarCapacityRow
		if err := rows.Scan(&i.ResourceID, &i.GDate, &i.Capacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCalendarUnavailable = `-- name: ListCalendarUnavailable :many
SELECT em.resource_id,
    g.date::date,
    COUNT(*)::bigint AS unavailable
FROM employee_states es
JOIN employees em ON em.id = es.employee_id
JOIN states s ON s.id = es.state_id
CROSS JOIN LATERAL generate_series(
    GREATEST(es.start_date, $1::date),
    LEAST(es.end_date, $2::date),
    INTERVAL '1 day'
) AS g(date)
WHERE s.is_available = FALSE
    AND em.deleted_at IS NULL
    AND es.end_date >= $1::date
    AND es.start_date <= $2::date
GROUP BY em.resource_id, g.date::date
`

type ListCalendarUnavailableParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type ListCalendarUnavailableRow struct {
	ResourceID  int64     `json:"resource_id"`
	GDate       time.Time `json:"g_date"`
	Unavailable int64     `json:"unavailable"`
}

// По-дневое количество недоступных сотрудников (состояния с is_available = false):
// разворачиваются только пересечения интервалов состояний с запрошенным диапазоном.
func (q *Queries) ListCalendarUnavailable(ctx context.Context, arg ListCalendarUnavailableParams) ([]ListCalendarUnavailableRow, error) {
	rows, err := q.db.Query(ctx, listCalendarUnavailable, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCalendarUnavailableRow{}
	for rows.Next() {
		var i ListCalendarUnavailableRow
		if err := rows.Scan(&i.ResourceID, &i.GDate, &i.Unavailable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResources = `-- name: ListResources :many
SELECT id, title, code
FROM resources
WHERE deleted_at IS NULL
ORDER BY id ASC
`

type ListResourcesRow struct {
	ID    int64  `json:"id"`
	Title string `json:"title"`
	Code  string `json:"code"`
}

func (q *Queries) ListResources(ctx context.Context) ([]ListResourcesRow, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesRow{}
	for rows.Next() {
		var i ListResourcesRow
		if err := rows.Scan(&i.ID, &i.Title, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
