// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process_scheduling.sql

package sqlc

import (
	"context"
)

const getProcessScheduling = `-- name: GetProcessScheduling :many
SELECT p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes processes,
    pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects projects
FROM processes p
JOIN projects pr ON p.project_id = pr.id
WHERE  deleted_at IS NULL
    AND (
        pr.owner_id = $1 OR
        $2 = 'ДП'
    )
ORDER BY pr.priority ASC
`

type GetProcessSchedulingParams struct {
	UserID int64       `json:"user_id"`
	Role   interface{} `json:"role"`
}

type GetProcessSchedulingRow struct {
	Process Process `json:"process"`
	Project Project `json:"project"`
}

func (q *Queries) GetProcessScheduling(ctx context.Context, arg GetProcessSchedulingParams) ([]GetProcessSchedulingRow, error) {
	rows, err := q.db.Query(ctx, getProcessScheduling, arg.UserID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProcessSchedulingRow{}
	for rows.Next() {
		var i GetProcessSchedulingRow
		if err := rows.Scan(
			&i.Process.ID,
			&i.Process.ProjectID,
			&i.Process.OwnerID,
			&i.Process.Title,
			&i.Process.StartDate,
			&i.Process.EndDate,
			&i.Process.CreatedAt,
			&i.Process.UpdatedAt,
			&i.Process.DeletedAt,
			&i.Project.ID,
			&i.Project.OwnerID,
			&i.Project.Code,
			&i.Project.StartDate,
			&i.Project.EndDate,
			&i.Project.Priority,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Project.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
