// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: process_scheduling.sql

package sqlc

import (
	"context"
)

const getProcessScheduling = `-- name: GetProcessScheduling :many
SELECT p.id, p.project_id, p.owner_id, p.title, p.start_date, p.end_date, p.created_at, p.updated_at, p.deleted_at,
    pr.id, pr.owner_id, pr.code, pr.start_date, pr.end_date, pr.priority, pr.created_at, pr.updated_at, pr.deleted_at
FROM processes p
JOIN projects pr ON p.project_id = pr.id
WHERE  p.deleted_at IS NULL
    AND (
        pr.owner_id = $1 OR
        $2 = 'ДП'
    )
ORDER BY pr.priority ASC
`

type GetProcessSchedulingParams struct {
	UserID int64       `json:"user_id"`
	Role   interface{} `json:"role"`
}

type GetProcessSchedulingRow struct {
	Process Process `json:"process"`
	Project Project `json:"project"`
}

func (q *Queries) GetProcessScheduling(ctx context.Context, arg GetProcessSchedulingParams) ([]GetProcessSchedulingRow, error) {
	rows, err := q.db.Query(ctx, getProcessScheduling, arg.UserID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProcessSchedulingRow{}
	for rows.Next() {
		var i GetProcessSchedulingRow
		if err := rows.Scan(
			&i.Process.ID,
			&i.Process.ProjectID,
			&i.Process.OwnerID,
			&i.Process.Title,
			&i.Process.StartDate,
			&i.Process.EndDate,
			&i.Process.CreatedAt,
			&i.Process.UpdatedAt,
			&i.Process.DeletedAt,
			&i.Project.ID,
			&i.Project.OwnerID,
			&i.Project.Code,
			&i.Project.StartDate,
			&i.Project.EndDate,
			&i.Project.Priority,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Project.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessesByProjectID = `-- name: ListProcessesByProjectID :many
SELECT id, project_id, owner_id, title, start_date, end_date, created_at, updated_at, deleted_at FROM processes
WHERE project_id = ANY($1::bigint[])
AND deleted_at IS NULL
`

func (q *Queries) ListProcessesByProjectID(ctx context.Context, projectIds []int64) ([]Process, error) {
	rows, err := q.db.Query(ctx, listProcessesByProjectID, projectIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Process{}
	for rows.Next() {
		var i Process
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.OwnerID,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
