// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: project_scheduling.sql

package sqlc

import (
	"context"
)

const listProjects = `-- name: ListProjects :many
SELECT id, owner_id, code, start_date, end_date, priority, created_at, updated_at, deleted_at FROM projects
WHERE deleted_at IS NULL
AND (
    $1 = 'ДП' OR
    owner_id = $2
)
ORDER BY priority ASC
`

type ListProjectsParams struct {
	Role   interface{} `json:"role"`
	UserID int64       `json:"user_id"`
}

// Project Scheduling
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.Role, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Code,
			&i.StartDate,
			&i.EndDate,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
