// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: task_scheduling.sql

package sqlc

import (
	"context"
)

const getResources = `-- name: GetResources :many
SELECT id, title, code, quantity, created_at, updated_at, deleted_at FROM resources
WHERE deleted_at IS NULL
`

func (q *Queries) GetResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, getResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskScheduling = `-- name: GetTaskScheduling :many
SELECT t.tasks, t.tasks, t.tasks, t.tasks, t.tasks, t.tasks, t.tasks, t.tasks tasks,
    p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes, p.processes processes,
    pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects, pr.projects projects,
    a.assignments, a.assignments, a.assignments, a.assignments, a.assignments, a.assignments, a.assignments assignments
FROM tasks t
JOIN processes p ON t.process_id = p.id
JOIN projects pr ON p.project_id = pr.id
LEFT JOIN assignments a ON t.id = a.task_id
WHERE tasks.deleted_at IS NULL
    AND (
        p.owner_id = $1 OR
        pr.owner_id = $1 OR
        $2 = 'ДП'
    )
ORDER BY pr.priority ASC
`

type GetTaskSchedulingParams struct {
	UserID int64       `json:"user_id"`
	Role   interface{} `json:"role"`
}

type GetTaskSchedulingRow struct {
	Task       Task       `json:"task"`
	Process    Process    `json:"process"`
	Project    Project    `json:"project"`
	Assignment Assignment `json:"assignment"`
}

func (q *Queries) GetTaskScheduling(ctx context.Context, arg GetTaskSchedulingParams) ([]GetTaskSchedulingRow, error) {
	rows, err := q.db.Query(ctx, getTaskScheduling, arg.UserID, arg.Role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskSchedulingRow{}
	for rows.Next() {
		var i GetTaskSchedulingRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ProcessID,
			&i.Task.Title,
			&i.Task.StartDate,
			&i.Task.EndDate,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Task.DeletedAt,
			&i.Process.ID,
			&i.Process.ProjectID,
			&i.Process.OwnerID,
			&i.Process.Title,
			&i.Process.StartDate,
			&i.Process.EndDate,
			&i.Process.CreatedAt,
			&i.Process.UpdatedAt,
			&i.Process.DeletedAt,
			&i.Project.ID,
			&i.Project.OwnerID,
			&i.Project.Code,
			&i.Project.StartDate,
			&i.Project.EndDate,
			&i.Project.Priority,
			&i.Project.CreatedAt,
			&i.Project.UpdatedAt,
			&i.Project.DeletedAt,
			&i.Assignment.ID,
			&i.Assignment.TaskID,
			&i.Assignment.ResourceID,
			&i.Assignment.Quantity,
			&i.Assignment.CreatedAt,
			&i.Assignment.UpdatedAt,
			&i.Assignment.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
