// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: resources.sql

package sqlc

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (title, code, quantity)
VALUES ($1, $2, $3::bigint)
RETURNING id, title, code, quantity, created_at, updated_at, deleted_at
`

type CreateResourceParams struct {
	Title    string `json:"title"`
	Code     string `json:"code"`
	Quantity int64  `json:"quantity"`
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Title, arg.Code, arg.Quantity)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
UPDATE resources
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
    AND deleted_at IS NULL
`

func (q *Queries) DeleteResource(ctx context.Context, resourceID int64) error {
	_, err := q.db.Exec(ctx, deleteResource, resourceID)
	return err
}

const findResource = `-- name: FindResource :one
SELECT id, title, code, quantity, created_at, updated_at, deleted_at
FROM resources
WHERE deleted_at IS NULL
	AND id = $1::bigint
`

func (q *Queries) FindResource(ctx context.Context, resourceID int64) (Resource, error) {
	row := q.db.QueryRow(ctx, findResource, resourceID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many

SELECT id, title, code, quantity, created_at, updated_at, deleted_at
FROM resources
WHERE deleted_at IS NULL
ORDER BY id ASC
`

// TODO: write CanUser...Resource
func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Code,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET
	title = $1,
	code = $2,
	quantity = $3::bigint,
	updated_at = NOW()
WHERE id = $4
    AND deleted_at IS NULL
RETURNING id, title, code, quantity, created_at, updated_at, deleted_at
`

type UpdateResourceParams struct {
	Title      string `json:"title"`
	Code       string `json:"code"`
	Quantity   int64  `json:"quantity"`
	ResourceID int64  `json:"resource_id"`
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Title,
		arg.Code,
		arg.Quantity,
		arg.ResourceID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Code,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
