// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: milestones.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countMilestones = `-- name: CountMilestones :one
SELECT COUNT(*)
FROM milestones m
JOIN processes p ON p.id = m.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE m.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint))
  )
  AND ($3::bigint = 0 OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
`

type CountMilestonesParams struct {
	ScopeView string `json:"scope_view"`
	UserID    int64  `json:"user_id"`
	OwnerID   int64  `json:"owner_id"`
}

func (q *Queries) CountMilestones(ctx context.Context, arg CountMilestonesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countMilestones, arg.ScopeView, arg.UserID, arg.OwnerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (process_id, title, content, color, date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, process_id, title, content, color, date, created_at, updated_at, deleted_at
`

type CreateMilestoneParams struct {
	ProcessID int64          `json:"process_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Color     sql.NullString `json:"color"`
	Date      time.Time      `json:"date"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProcessID,
		arg.Title,
		arg.Content,
		arg.Color,
		arg.Date,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
UPDATE milestones
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) DeleteMilestone(ctx context.Context, milestoneID int64) error {
	_, err := q.db.Exec(ctx, deleteMilestone, milestoneID)
	return err
}

const findMilestone = `-- name: FindMilestone :one
SELECT id, process_id, title, content, color, date, created_at, updated_at, deleted_at
FROM milestones
WHERE id = $1
	AND deleted_at IS NULL
`

func (q *Queries) FindMilestone(ctx context.Context, milestoneID int64) (Milestone, error) {
	row := q.db.QueryRow(ctx, findMilestone, milestoneID)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMilestones = `-- name: ListMilestones :many
SELECT m.id, m.process_id, m.title, m.content, m.color, m.date, m.created_at, m.updated_at, m.deleted_at
FROM milestones m
JOIN processes p ON p.id = m.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE m.deleted_at IS NULL
  AND (
    $1::text = 'all' OR
    ($1::text = 'parent' AND p.owner_id = $2::bigint) OR
    ($1::text = 'ancestor' AND (p.owner_id = $2::bigint OR pr.owner_id = $2::bigint))
  )
  AND ($3::bigint = 0 OR p.owner_id = $3::bigint OR pr.owner_id = $3::bigint)
ORDER BY m.id ASC
LIMIT $5::bigint OFFSET $4::bigint
`

type ListMilestonesParams struct {
	ScopeView  string `json:"scope_view"`
	UserID     int64  `json:"user_id"`
	OwnerID    int64  `json:"owner_id"`
	PageOffset int64  `json:"page_offset"`
	PageLimit  int64  `json:"page_limit"`
}

func (q *Queries) ListMilestones(ctx context.Context, arg ListMilestonesParams) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestones,
		arg.ScopeView,
		arg.UserID,
		arg.OwnerID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Milestone{}
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.ProcessID,
			&i.Title,
			&i.Content,
			&i.Color,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ownerChain = `-- name: OwnerChain :one
SELECT COALESCE(pr.owner_id, 0)::bigint AS project_owner,
       COALESCE(p.owner_id, 0)::bigint  AS process_owner
FROM milestones m
JOIN processes p ON p.id = m.process_id
JOIN projects pr ON pr.id = p.project_id
WHERE m.id = $1::bigint
	AND m.deleted_at IS NULL
	AND p.deleted_at IS NULL
	AND pr.deleted_at IS NULL
`

type OwnerChainRow struct {
	ProjectOwner int64 `json:"project_owner"`
	ProcessOwner int64 `json:"process_owner"`
}

func (q *Queries) OwnerChain(ctx context.Context, id int64) (OwnerChainRow, error) {
	row := q.db.QueryRow(ctx, ownerChain, id)
	var i OwnerChainRow
	err := row.Scan(&i.ProjectOwner, &i.ProcessOwner)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET
	process_id = $1,
	title = $2,
	content = $3,
	color = $4,
	date = $5,
	updated_at = NOW()
WHERE id = $6
	AND deleted_at IS NULL
RETURNING id, process_id, title, content, color, date, created_at, updated_at, deleted_at
`

type UpdateMilestoneParams struct {
	ProcessID   int64          `json:"process_id"`
	Title       string         `json:"title"`
	Content     string         `json:"content"`
	Color       sql.NullString `json:"color"`
	Date        time.Time      `json:"date"`
	MilestoneID int64          `json:"milestone_id"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ProcessID,
		arg.Title,
		arg.Content,
		arg.Color,
		arg.Date,
		arg.MilestoneID,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProcessID,
		&i.Title,
		&i.Content,
		&i.Color,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
