// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
	"time"
)

type Milestone struct {
	ID        int64          `json:"id"`
	ProcessID int64          `json:"process_id"`
	Title     string         `json:"title"`
	Content   string         `json:"content"`
	Color     sql.NullString `json:"color"`
	Date      time.Time      `json:"date"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}
